import type { CourseData } from './types'

const module5: CourseData = {
  moduleId: 5,
  title: 'AI Tools Beyond ChatGPT: Image, Audio & More',
  subtitle: 'AI Tools Beyond ChatGPT',
  nextModuleId: 6,
  lessons: [
    {
      id: 0,
      title: 'The AI Tool Landscape',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 5 · Lesson 1',
          icon: '🧰',
          title: 'ChatGPT is just the beginning.',
          body: [
            "You've spent four modules getting comfortable with ChatGPT, and that foundation is real. But the AI world is much bigger — and some of the most useful tools aren't ChatGPT at all.",
            "In this module, you'll explore the broader toolkit: image generators, transcription tools, specialized AI for specific jobs, and how to build a personal AI setup that actually works for you.",
          ],
          sub: 'One tool in a whole toolbox.',
        },
        {
          type: 'concept',
          eyebrow: 'The landscape',
          icon: '🗺️',
          title: 'AI tools fall into a few main categories.',
          body: ["Think of AI tools the way you think about any professional toolkit. A contractor doesn't use a hammer for every job. Neither should you."],
          list: {
            items: [
              '<strong>Text &amp; writing</strong> — ChatGPT, Claude, Gemini. For conversations, drafts, editing, research.',
              '<strong>Image generation</strong> — DALL-E, Midjourney, Adobe Firefly, Canva AI. For creating visuals from descriptions.',
              '<strong>Audio &amp; transcription</strong> — Otter.ai, Fireflies. For meeting notes, voice-to-text, and video editing.',
              '<strong>Specialized tools</strong> — AI built into apps you already use, or tools built for your specific industry.',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'The key insight',
          icon: '💡',
          title: "You don't need all of them. You need the right ones.",
          body: [
            "New AI tools launch every week. If you tried to keep up with all of them, it would be a full-time job — and a frustrating one.",
            "The goal isn't to use every tool. It's to identify the 2–3 tools that solve real problems in your actual work or life, and get genuinely good at those.",
          ],
          highlight: 'Depth with a few tools beats dabbling with many.',
        },
        {
          type: 'concept',
          eyebrow: 'Tools to know',
          icon: '🔭',
          title: 'Six tools worth knowing about right now.',
          body: ["Here's a quick introduction to the tools you'll learn more about in this module:"],
          platformGrid: [
            { name: '🎨 DALL-E (in ChatGPT)', detail: 'Image generation built into ChatGPT Plus. Describe an image in conversation and get a professional-quality result.' },
            { name: '🎭 Midjourney', detail: 'The most powerful image generator for creative and artistic work. Higher learning curve, stunning results.' },
            { name: '🦦 Otter.ai', detail: 'Records and transcribes meetings automatically. Generates summaries and action items when the call ends.' },
            { name: '🔥 Adobe Firefly', detail: 'AI image generation designed for commercial use. Safe for business — no copyright concerns.' },
            { name: '🔍 Perplexity AI', detail: 'An AI-powered search engine. Answers questions with cited sources — great for research.' },
            { name: '✨ Canva AI', detail: 'AI features built into Canva. Create social graphics, presentations, and custom images with AI assistance.' },
          ],
        },
        {
          type: 'compare',
          eyebrow: 'Choosing the right tool',
          title: 'Using the right tool changes everything.',
          bad: { label: 'Using one tool for everything', text: 'I asked ChatGPT to make me a logo. It wrote a description of what the logo should look like.' },
          good: { label: 'Using the right tool', text: 'I described my logo idea to Canva AI and had three variations to choose from in 60 seconds.' },
          highlight: 'Match the tool to the task — not the task to the tool you already know.',
        },
        {
          type: 'concept',
          eyebrow: 'Evaluating new tools',
          icon: '🔍',
          title: 'How to decide if a new AI tool is worth your time.',
          body: ["When a new tool pops up in your feed, here's a quick 3-question test before you invest time in it:"],
          list: {
            items: [
              'Does it solve a real problem I actually have — not just a theoretical one?',
              'Is there a free version or trial so I can test it before paying?',
              'Can I get 80% of the benefit in 20 minutes, or does it require weeks of learning?',
            ],
            negative: false,
          },
          body2: 'If the answer to all three is yes, it\'s worth trying.',
        },
        {
          type: 'exercise',
          eyebrow: 'Try it now',
          icon: '🎯',
          title: 'Pick one new tool to explore this week.',
          body: ["You're going to learn about several tools in this module. Before you go further, pick one you want to try — just one."],
          prompt: "Open a new tab and visit one of these:\n\n• Otter.ai — free account, try transcribing a voice memo\n• Perplexity.ai — free, try asking a research question\n• Canva.com — free, try the AI features in a design\n\nYour only job: spend 10 minutes exploring. Notice what it does well and where it falls short.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 1 complete',
          icon: '✅',
          title: 'What you now know about the AI tool landscape.',
          summaryList: [
            'You know AI tools fall into categories — text, image, audio, and specialized.',
            'You understand that using the right tool for the job beats using one tool for everything.',
            'You have a 3-question test for evaluating any new tool before you invest time in it.',
          ],
        },
      ],
    },
    {
      id: 1,
      title: 'Image Generation: Making Visuals with Words',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 5 · Lesson 2',
          icon: '🎨',
          title: 'What if you could create any image just by <em>describing</em> it?',
          body: [
            "A year ago, if you needed a custom image for a presentation or social post, you had two options: search stock photo sites and settle for something generic, or pay a designer and wait.",
            "Image generation AI changes that completely. Describe what you want in plain English — and you'll have a professional-quality image in seconds.",
          ],
          sub: 'No design skills required.',
        },
        {
          type: 'concept',
          eyebrow: 'How it works',
          icon: '🧠',
          title: "Image AI doesn't search for images — it creates new ones.",
          body: [
            "Image generation AI has learned from hundreds of millions of images. When you describe an image, it doesn't find one — it generates a brand new image that matches your description.",
            "That means you're not limited to what exists. You can create images of things that have never been photographed, in styles that have never been tried, for situations completely specific to you.",
          ],
          highlight: 'Every image you generate is unique. It exists because you asked for it.',
        },
        {
          type: 'concept',
          eyebrow: 'The main tools',
          icon: '🖼️',
          title: 'Four image tools worth knowing — each with a different strength.',
          body: ["The right image tool depends on what you're creating and how much control you want:"],
          platformGrid: [
            { name: '🎨 DALL-E (in ChatGPT)', detail: 'Built into ChatGPT Plus. Easiest to use — just describe your image in the same chat you\'re already in. Great starting point.' },
            { name: '🎭 Midjourney', detail: 'The most artistically powerful option. Used by professional designers. Higher learning curve, but the results are stunning.' },
            { name: '🔥 Adobe Firefly', detail: 'Designed for commercial use — commercially safe, no copyright concerns. Integrates with Photoshop and Illustrator.' },
            { name: '✨ Canva AI', detail: 'AI image generation inside Canva. Easiest for non-designers who already use Canva for their graphics.' },
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Writing great prompts',
          icon: '✍️',
          title: 'Image prompts are just descriptions — with a little technique.',
          body: ["The better your description, the better your image. Think about what a photographer would need to know to take the shot you have in mind:"],
          list: {
            items: [
              "<strong>Subject:</strong> What's in the image? Who or what is the focus?",
              '<strong>Style:</strong> Photo-realistic? Illustration? Watercolor? 3D render?',
              '<strong>Mood:</strong> Professional and clean? Warm and inviting? Bold and energetic?',
              '<strong>Details:</strong> Colors, setting, time of day, perspective, background.',
            ],
            negative: false,
          },
        },
        {
          type: 'compare',
          eyebrow: 'Prompt quality',
          title: 'Specificity is the difference between generic and great.',
          bad: { label: 'Vague prompt', text: 'A person at work.' },
          good: { label: 'Specific prompt', text: "A confident professional woman in her 40s at a bright, organized home office desk, smiling naturally, warm afternoon light, photorealistic." },
          highlight: 'Treat your image prompt like art direction. The more specific you are, the closer you get to what you actually want.',
        },
        {
          type: 'concept',
          eyebrow: 'Real uses',
          icon: '💼',
          title: 'Where image AI saves real time for real people.',
          body: ["You don't need to be a designer or creative professional to benefit from image AI. Some of the most practical uses are surprisingly everyday:"],
          list: {
            items: [
              "Blog and article header images — custom, on-brand, not generic stock photos.",
              "Social media graphics when you don't have a designer on call.",
              "Presentation visuals — concept illustrations, process diagrams, scene-setting images.",
              "Product mockups and marketing ideas to test before investing in production.",
            ],
            negative: false,
          },
        },
        {
          type: 'exercise',
          eyebrow: 'Try it now',
          icon: '🎨',
          title: 'Create your first AI image.',
          body: ["The best way to understand image AI is to try it. Here's how to do it right now, for free:"],
          prompt: "Option 1 — ChatGPT Plus:\nOpen ChatGPT, click the image icon, and describe what you want:\n\"A [describe your subject] in a [style: photo/illustration], [mood], [setting details].\"\n\nOption 2 — Free (Canva):\nGo to canva.com → click 'Create a design' → find 'Text to Image' in the editor.\n\nTry at least 2 variations. Change one word and see how it changes the result.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 2 complete',
          icon: '✅',
          title: 'You can now create custom images with words.',
          summaryList: [
            "You know how image generation AI works — it creates new images, not searches for existing ones.",
            "You know the four main tools and when to use each one.",
            "You can write a specific, effective image prompt using subject, style, mood, and details.",
            "You've tried it yourself and seen how small changes in your prompt change the result.",
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Audio & Transcription: AI That Listens',
      meta: '9 slides · ~7 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 5 · Lesson 3',
          icon: '🎙️',
          title: 'AI that turns your meetings into notes — automatically.',
          body: [
            "Think about how much of your work week happens in meetings, on calls, or in conversations. And then think about how little of it you actually capture and act on.",
            "Transcription AI changes this. It listens to your meetings, writes down everything that was said, and generates summaries and action items — so you can focus on the conversation instead of frantically taking notes.",
          ],
          sub: 'Every important conversation, captured.',
        },
        {
          type: 'concept',
          eyebrow: 'What is transcription AI?',
          icon: '📝',
          title: 'Transcription AI converts spoken words into written text — in real time.',
          body: [
            "Transcription AI listens to audio — a live meeting, a recorded call, a voice memo, a podcast — and converts it to text. The best tools go further: they identify who said what, summarize key points, and highlight action items.",
            "AI has made transcription dramatically more accurate, far more affordable (often free), and much more useful with intelligent summarization layered on top.",
          ],
          highlight: 'You stop taking notes. The AI takes them for you.',
        },
        {
          type: 'concept',
          eyebrow: 'The leading tool',
          icon: '🦦',
          title: "Otter.ai: the meeting note-taker you never have to remind.",
          body: ["Otter.ai is the most widely used transcription tool for meetings and calls. It integrates directly with Zoom, Google Meet, and Teams — joining your calls automatically."],
          list: {
            items: [
              'Records and transcribes your meeting in real time',
              'Identifies and labels different speakers throughout',
              'Generates a summary and action items when the meeting ends',
              'Free plan: 300 minutes per month — enough for daily use',
              'Searchable: find any moment from any past meeting by keyword',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Other tools to know',
          icon: '🔊',
          title: 'The rest of the audio AI toolkit.',
          body: ["Otter is the easiest to start with, but depending on your needs, these are also worth knowing:"],
          platformGrid: [
            { name: '🔥 Fireflies.ai', detail: 'Similar to Otter, with stronger CRM integrations. Good for sales teams who need call notes in HubSpot or Salesforce.' },
            { name: '📱 Rev', detail: 'Human + AI transcription. More accurate for difficult audio, accents, or industry jargon. Paid, but high quality.' },
            { name: '🤫 Whisper (OpenAI)', detail: 'Open-source transcription AI from OpenAI. Powers many apps behind the scenes. Free to use via third-party tools.' },
            { name: '🎬 Descript', detail: 'Records, transcribes, AND edits. Edit your video by editing the transcript. Powerful for content creators.' },
          ],
        },
        {
          type: 'concept',
          eyebrow: 'The workflow',
          icon: '📅',
          title: 'The meeting AI workflow: join, record, review.',
          body: ["Most professionals who use meeting AI describe it the same way: they can't imagine going back. Here's the typical flow:"],
          list: {
            items: [
              '<strong>Before the meeting:</strong> Set up Otter to join automatically via calendar integration.',
              '<strong>During the meeting:</strong> Focus on the conversation — not your notes.',
              '<strong>After the meeting:</strong> Review the AI-generated summary (usually 2–3 minutes). Share action items.',
              '<strong>Later:</strong> Search the transcript any time you need to recall something specific.',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Beyond meetings',
          icon: '💬',
          title: "Transcription isn't just for meetings.",
          body: ["Once you have a transcription tool, you'll find uses everywhere:"],
          list: {
            items: [
              '<strong>Voice memos:</strong> Dictate ideas on your phone, get searchable text to work from.',
              '<strong>Interviews and research:</strong> Record conversations and get a searchable transcript.',
              '<strong>Podcast or video content:</strong> Auto-generate captions and show notes.',
              '<strong>Customer calls:</strong> Capture feedback and commitments without writing mid-call.',
            ],
            negative: false,
          },
          highlight: 'Anything you can say, you can now have as text.',
        },
        {
          type: 'concept',
          eyebrow: 'Video editing with AI',
          icon: '🎬',
          title: 'Descript: edit video by editing text.',
          body: [
            "Descript deserves its own slide. It transcribes your video — and then lets you edit the video by editing the transcript.",
            "Delete a sentence from the transcript, and the corresponding video clip disappears. Fix a filler word by typing over it. It makes video editing accessible to people who've never touched video editing software.",
          ],
          list: {
            items: [
              'Record screen and webcam simultaneously',
              'Transcribe your recording automatically',
              'Edit video by editing the text — like a Word doc',
              "Remove filler words ('um', 'uh') in one click",
              'Free plan available to get started',
            ],
            negative: false,
          },
        },
        {
          type: 'exercise',
          eyebrow: 'Try it now',
          icon: '🎙️',
          title: 'Transcribe something today.',
          body: ["One of the best ways to see how useful transcription AI is: try it on something you actually need."],
          prompt: "Go to otter.ai and create a free account.\n\nThen try one of these:\n• Join your next meeting with Otter running (it will join and transcribe automatically)\n• Upload a voice memo or short recording from your phone\n• Use the Otter mobile app to record yourself speaking for 2–3 minutes\n\nAfterward: review the transcript and summary. What did the AI capture that you would have forgotten?",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 3 complete',
          icon: '✅',
          title: 'Your meetings are now captured automatically.',
          summaryList: [
            'You know what transcription AI does and why it saves real time in your work week.',
            'You know Otter.ai — how to set it up and what to expect from it.',
            'You know the broader audio AI toolkit for different needs and use cases.',
            'You have a clear workflow for using meeting AI from start to finish.',
          ],
          template: true,
          templateText: "Quick-start: Otter.ai\n1. Sign up at otter.ai (free)\n2. Connect your calendar (Zoom / Meet / Teams)\n3. Let it join your next meeting\n4. Review the AI summary afterward\n5. Share action items with your team",
        },
      ],
    },
    {
      id: 3,
      title: 'Specialized AI for Your Work',
      meta: '9 slides · ~7 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 5 · Lesson 4',
          icon: '🎯',
          title: "There's probably an AI tool built specifically for what <em>you</em> do.",
          body: [
            "ChatGPT is a general-purpose AI. It can help with almost anything — but it's designed for almost everyone. Specialized AI tools are different: they're built for specific tasks, industries, and workflows.",
            "In this lesson, you'll get a map of where AI already exists in the tools you use — and how to find tools made specifically for your type of work.",
          ],
          sub: 'The right tool for your specific job.',
        },
        {
          type: 'concept',
          eyebrow: 'Writing & editing tools',
          icon: '✍️',
          title: 'AI that helps you write and edit better, faster.',
          body: ["Some of the most mature AI tools are in the writing and editing category. You may already use some of them without thinking of them as AI:"],
          platformGrid: [
            { name: '✅ Grammarly', detail: 'AI writing assistant. Catches grammar, tone, and clarity issues in real time. Works across most web apps and email.' },
            { name: '📝 Notion AI', detail: 'AI built into Notion. Summarize notes, draft content, extract action items from meeting notes.' },
            { name: '🚀 Jasper', detail: 'AI writing platform built for marketing. Trained on high-performing marketing copy.' },
            { name: "📧 Gmail / Copilot", detail: "AI built into Gmail ('Help me write') and Microsoft 365 (Copilot). Draft emails and summarize threads." },
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Research tools',
          icon: '🔍',
          title: 'AI that finds and synthesizes information for you.',
          body: ["Research is one of the highest-value use cases for AI — and there are tools specifically designed to make it faster and more reliable:"],
          list: {
            items: [
              '<strong>Perplexity AI</strong> — An AI search engine that gives you answers with cited sources. Better than Google for research questions because it synthesizes, not just links.',
              '<strong>NotebookLM (Google)</strong> — Upload your own documents and let AI analyze them together. Great for research reports, industry reading, long policy documents.',
              '<strong>ChatGPT with search</strong> — ChatGPT Plus can search the web in real time, combining conversation with current information.',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Design tools',
          icon: '🎨',
          title: 'AI that helps you create professional visuals — no design skills needed.',
          body: ["If you've ever wished you could create something that looked professional without hiring a designer, these tools are for you:"],
          list: {
            items: [
              '<strong>Canva AI</strong> — Magic Design, text-to-image, background removal, and AI-assisted layouts. Free to use.',
              '<strong>Adobe Firefly</strong> — Generative fill and AI image creation. Commercially safe — no copyright concerns for business use.',
              '<strong>Microsoft Designer</strong> — Free with a Microsoft account. Creates social media graphics, invitations, and presentations from a text description.',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'AI in your existing tools',
          icon: '🔧',
          title: 'AI is being built into tools you already use.',
          body: ["You don't always have to go looking for a new AI tool. AI is being added to the software you already have — sometimes without a big announcement:"],
          list: {
            items: [
              '<strong>Microsoft 365 Copilot</strong> — AI in Word, Excel, PowerPoint, Outlook, and Teams.',
              '<strong>Google Workspace AI</strong> — AI in Docs, Sheets, Gmail, and Slides.',
              '<strong>Salesforce Einstein</strong> — AI built into Salesforce CRM for sales insights and automation.',
              '<strong>Zoom AI Companion</strong> — Meeting summaries and action items inside Zoom.',
              '<strong>HubSpot AI</strong> — AI-generated email copy, sequences, and customer insights.',
            ],
            negative: false,
          },
          highlight: 'Before signing up for something new, check if your existing software already has AI built in.',
        },
        {
          type: 'concept',
          eyebrow: 'Finding your tools',
          icon: '🧭',
          title: 'How to find AI tools built for your specific job.',
          body: ["The fastest way to find relevant specialized tools: just ask ChatGPT."],
          prompt: '"I\'m a [your job title] at a [describe your company or industry]. What AI tools are specifically useful for the work I do? Give me 5–10 options with a one-sentence description of each."',
          body2: 'Take the list and research the top 2–3. You\'ll often find tools built specifically for your industry that you\'ve never heard of.',
        },
        {
          type: 'compare',
          eyebrow: 'The right approach',
          title: 'Trying every tool wastes time. Finding the right one saves it.',
          bad: { label: 'Tool overload', text: "I have accounts for 12 AI tools. I don't really use any of them consistently." },
          good: { label: 'Focused stack', text: "I use ChatGPT for writing, Otter for meetings, and Perplexity when I need to research something. That's it." },
          highlight: 'A consistent workflow with 3 good tools beats a scattered approach with 12.',
        },
        {
          type: 'exercise',
          eyebrow: 'Try it now',
          icon: '🔍',
          title: 'Find one specialized tool for your work.',
          body: ["Use the prompt from slide 6 to find AI tools built for your job. Then pick one to investigate:"],
          prompt: "Step 1: Open ChatGPT and ask:\n\"What are the best AI tools for someone who works as a [your job title or role]? What specific problems do they solve?\"\n\nStep 2: Pick one tool that solves a real problem you actually have.\n\nStep 3: Search the tool name + 'free plan' to see if you can test it.\n\nWrite down: what does this tool do, and what is one specific way you'd use it this week?",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 4 complete',
          icon: '✅',
          title: 'You know where to find AI built for your specific work.',
          summaryList: [
            'You know the main categories of specialized AI tools — writing, research, design, and industry-specific.',
            'You know to check your existing software for built-in AI before adopting something new.',
            'You have a prompt for finding AI tools built specifically for your job title and industry.',
            'You understand why a focused set of tools beats trying everything that comes along.',
          ],
        },
      ],
    },
    {
      id: 4,
      title: 'Building Your Personal AI Stack',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 5 · Lesson 5',
          icon: '🏗️',
          title: "You don't need 20 tools. You need the right <em>3.</em>",
          body: [
            "By now you've been introduced to more AI tools than you can possibly adopt at once. That's intentional — awareness is the first step.",
            "This lesson is about narrowing down. You're going to design your personal AI stack: the small set of tools you'll actually use, consistently, in your real workflow.",
          ],
          sub: 'Less is more. Depth beats breadth.',
        },
        {
          type: 'concept',
          eyebrow: 'What is an AI stack?',
          icon: '📚',
          title: "Your AI stack is the set of tools you use regularly — and rely on.",
          body: [
            "'Stack' is borrowed from tech, but the concept is simple: it's your personal toolkit. The tools you've made a real part of how you work.",
            "A good AI stack has three qualities: it solves real problems you actually have, it fits your existing workflow without creating a new one, and it's small enough that you actually use it — not just have accounts for.",
          ],
          highlight: 'One tool you use every day is worth ten you log into twice.',
        },
        {
          type: 'concept',
          eyebrow: 'The starter stack',
          icon: '🎯',
          title: 'A simple starter stack for most people.',
          body: ["Here's the setup most people find themselves using consistently after a few months:"],
          stackCards: [
            { num: '1', name: 'ChatGPT (or Claude)', desc: 'Your primary AI assistant. For writing, research, thinking through problems, and anything text-based. Use it every day.' },
            { num: '2', name: 'One image tool', desc: 'DALL-E (in ChatGPT Plus), Canva AI, or Adobe Firefly. For creating visuals when you need them — not for every task, just the right ones.' },
            { num: '3', name: 'One transcription tool', desc: "Otter.ai for most people. For meeting notes, voice memos, and capturing conversations you'd otherwise lose." },
          ],
          body2: 'Three tools. Each solving a different kind of problem.',
        },
        {
          type: 'concept',
          eyebrow: 'Evaluating new tools',
          icon: '🧪',
          title: 'When a new tool appears, ask these four questions.',
          body: ["New tools will keep appearing. Here's how to evaluate them quickly without getting sucked in:"],
          list: {
            items: [
              "<strong>What specific problem does this solve?</strong> If you can't name the problem, move on.",
              "<strong>Is there a free version to test?</strong> Never pay for a tool you haven't tried.",
              "<strong>Will this replace something in my stack, or just add to it?</strong> Replacing is better than adding.",
              "<strong>Can I get meaningful value in under 30 minutes?</strong> Good tools don't require weeks of onboarding.",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Staying current',
          icon: '📡',
          title: 'How to stay up to date without drowning in AI news.',
          body: ["The AI landscape changes fast. But you don't need to track every development — you just need to know what's relevant to you."],
          list: {
            items: [
              '<strong>Pick one newsletter:</strong> The AI industry produces hundreds. Pick one (The Rundown, Morning Brew AI, or similar) and stick to it.',
              "<strong>Ask ChatGPT about updates:</strong> 'What's changed in AI tools for [your industry] in the past few months?' works well.",
              '<strong>Follow one or two voices you trust</strong> on LinkedIn or YouTube — people who explain clearly, not just hype.',
              "<strong>Set a monthly review:</strong> Once a month, ask yourself: is my current AI stack still working? Is there something better?",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'The bigger picture',
          icon: '🌟',
          title: "You're not just learning tools. You're building a new way of working.",
          body: [
            "The people who get the most value from AI aren't the ones who know about the most tools. They're the ones who've made AI a consistent part of how they work — like email or a calendar.",
            "The goal isn't mastery of every tool. It's an AI-first mindset: when you face a problem, your first instinct is to ask whether AI could help. That shift is worth more than any individual tool.",
          ],
          highlight: "AI-first doesn't mean AI-only. It means you always ask: is there a smarter way to do this?",
        },
        {
          type: 'exercise',
          eyebrow: 'Design your stack',
          icon: '🏗️',
          title: 'Build your personal AI stack right now.',
          body: ["Take 5 minutes to write down your stack. Be specific about what you'll use each tool for."],
          prompt: "Open a note, doc, or piece of paper. Fill this in:\n\n1. My primary AI assistant: [ChatGPT / Claude / other]\n   → I'll use it for: [list 2–3 specific use cases]\n\n2. My image tool: [DALL-E / Canva AI / Adobe Firefly / skip for now]\n   → I'll use it for: [specific use case]\n\n3. My transcription tool: [Otter.ai / Fireflies / other / skip for now]\n   → I'll use it for: [specific use case]\n\n4. One specialized tool for my work: [name it]\n   → I'll use it for: [specific use case]\n\nYou now have a plan — not a list of things to try, but a plan for what you'll actually use.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 5 complete · Module 5 complete',
          icon: '🎉',
          title: "You've built your AI stack. Now use it.",
          summaryList: [
            "You understand what an AI stack is and why depth with a few tools beats dabbling with many.",
            "You have a clear starter stack as your foundation — three tools, three different problems solved.",
            "You have a framework for evaluating new tools quickly as they appear.",
            "You know how to stay current without getting overwhelmed by AI news.",
            "You've designed your own personal AI setup.",
          ],
          highlight: 'Module 6 is next: Your AI Life — Staying Current and Going Further. You\'ll bring everything together and build a plan for how AI grows with you over the next year.',
        },
      ],
    },
  ],
  quiz: [
    {
      q: "What's the key difference between image generation AI and image search?",
      options: [
        'Image AI finds the best matching image from the web',
        "Image AI creates brand-new images that didn't exist before",
        'Image AI automatically edits and improves your existing photos',
        'Image AI downloads stock photos from licensed libraries',
      ],
      correct: 1,
      feedback: "Image generation AI creates entirely new images from your description — it doesn't search for or download existing ones. Every image it produces is unique.",
    },
    {
      q: 'Which tool is best known for automatically joining your meetings, transcribing them, and generating summaries?',
      options: ['Adobe Firefly', 'Midjourney', 'Otter.ai', 'Perplexity AI'],
      correct: 2,
      feedback: 'Otter.ai is a leading meeting transcription tool that joins calls automatically, transcribes in real time, and generates summaries and action items when the meeting ends.',
    },
    {
      q: "What is an 'AI stack'?",
      options: [
        'A type of data architecture used to train AI models',
        'The set of AI tools you use consistently in your regular workflow',
        'A technique for writing better prompts in ChatGPT',
        'A hardware setup for running AI locally on your computer',
      ],
      correct: 1,
      feedback: "Your AI stack is your personal toolkit — the specific tools you use consistently. Quality and consistency with a few tools beats having accounts for many.",
    },
    {
      q: 'When writing an image prompt, what approach produces better results?',
      options: [
        'Keep it as short and vague as possible',
        'Use technical design jargon to sound professional',
        'Be specific about subject, style, mood, and key details',
        'Ask the AI to choose the style for you',
      ],
      correct: 2,
      feedback: "Specific image prompts — describing subject, style, mood, and key details — produce much better results than vague descriptions. Treat your prompt like art direction.",
    },
    {
      q: "When evaluating a new AI tool that shows up in your feed, what's the most important first question to ask?",
      options: [
        'How much does it cost per month?',
        'What specific problem does this solve for me?',
        'Does it have a mobile app?',
        'How many users does it have?',
      ],
      correct: 1,
      feedback: "The most important question is whether the tool solves a real problem you actually have. Without a specific use case in mind, even a great tool won't become part of your workflow.",
    },
  ],
}

export default module5
