import type { CourseData } from './types'

const module1: CourseData = {
  moduleId: 1,
  title: 'AI 101: What It Is & Why It Matters',
  subtitle: 'Module 1',
  nextModuleId: 2,
  lessons: [
    {
      id: 0,
      title: 'What Even Is AI?',
      meta: '8 slides · ~5 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 1 · Lesson 1',
          icon: '🧠',
          title: 'What Even Is AI?',
          body: ["By the end of this lesson, you'll know exactly what AI is — in plain English — and you'll be able to explain it to anyone. That alone puts you ahead of most people."],
          sub: "Let's start at the very beginning.",
        },
        {
          type: 'concept',
          eyebrow: "Let's be honest",
          icon: '📰',
          title: "You've heard this word everywhere.",
          body: [
            "TV. News. Coworkers. Family dinner. AI is the buzzword of the decade.",
            'And yet — when someone asks you what it actually means, the honest answer is probably: <em>"I\'m not totally sure."</em>',
            "That's not a failure. Nobody explained it properly. Until now.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Clearing the air',
          icon: '❌',
          title: 'First — what AI is <em>not.</em>',
          body: ['Before we define it, let\'s get some myths out of the way.'],
          list: {
            items: [
              'A robot that thinks like a human',
              "A system that's smarter than people in every way",
              "Something that's secretly plotting to take over",
              'Science fiction brought to life',
              "A mysterious black box that nobody understands",
            ],
            negative: true,
          },
        },
        {
          type: 'concept',
          eyebrow: 'The simple truth',
          icon: '🔍',
          title: 'AI is a very fast, very well-read <em>pattern-matcher.</em>',
          body: [
            "Here's the most honest definition: AI learns patterns from enormous amounts of human writing, images, and data — and then uses those patterns to respond to whatever you say or show it.",
            "It doesn't 'think.' It doesn't 'feel.' It matches patterns at an astonishing scale and speed.",
            "That's it. The whole thing.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'An analogy that clicks',
          icon: '📚',
          title: 'Imagine someone who has read... <em>everything.</em>',
          body: [
            'Imagine a person who read every book, article, website, email, manual, recipe, and forum post ever written. Billions of pages.',
            "Now imagine you can ask them anything and they'll respond based on all of it — in seconds.",
            "That's roughly what a modern AI tool is.",
          ],
          highlight: 'Incredibly well-read. Incredibly fast. And sometimes confidently wrong — more on that later.',
        },
        {
          type: 'concept',
          eyebrow: "Two kinds you'll actually use",
          icon: '💬',
          title: 'There are two types of AI in your world.',
          body: [
            "<strong>Conversational AI:</strong> You type a message, it responds. Like a conversation. ChatGPT, Claude, and Google Gemini are all this type. We'll focus here — it's the most useful.",
            "<strong>Specialized AI:</strong> Built for one specific job. Grammar checking, image creation, transcription. Tools like Grammarly or the AI inside your phone camera.",
            'Once you understand conversational AI, everything else will make sense.',
          ],
        },
        {
          type: 'takeaway',
          eyebrow: 'Key Takeaway',
          icon: '✨',
          title: "AI is a powerful tool — not a person, not magic, not a threat.",
          body: [
            "You now understand something most people don't: AI isn't mysterious or unknowable.",
            "It's a sophisticated pattern-matching system trained on human-created content. It's impressive, it's useful, and you can absolutely learn to use it.",
          ],
          highlight: 'AI is a tool. A very powerful one. And like any tool, it does what you ask — when you know how to ask.',
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: 'Your first exercise.',
          body: ["Open <strong>chatgpt.com</strong> in a new browser tab and type this into the text box. <em>Don't have an account yet? No problem — sign up for free in about 2 minutes. See the guide below.</em>"],
          prompt: "Hi! I'm brand new to AI. I just learned that you work by matching patterns from text you were trained on. Can you explain what that means in simple terms — like you're talking to someone who's never used AI before?",
          body2: "Read what comes back. Notice: it's a conversation. You asked, it answered. That's the whole game.",
          setupGuide: true,
        },
      ],
    },
    {
      id: 1,
      title: "The Tools You've Heard About",
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 1 · Lesson 2',
          icon: '🛠️',
          title: "The Tools You've Heard About",
          body: ["ChatGPT. Gemini. Copilot. Claude. There are a lot of AI tools out there. In this lesson we'll cut through the confusion, explain the main ones, and help you pick one to start with."],
          sub: 'Spoiler: they all work the same way.',
        },
        {
          type: 'concept',
          eyebrow: 'Good news first',
          icon: '🚗',
          title: 'Learn one — and you basically know them all.',
          body: ['Most major AI tools work in fundamentally the same way. You type something, it responds. The interface changes a little. The underlying idea stays the same.'],
          highlight: "Think of it like cars. A Toyota and a Ford work differently under the hood. But once you know how to drive, you can drive either one.",
        },
        {
          type: 'tool',
          eyebrow: 'Tool 1',
          icon: '🤖',
          toolName: 'ChatGPT',
          toolMaker: 'by OpenAI',
          toolUrl: 'chatgpt.com',
          body: [
            "The one that started the mainstream AI conversation. Free to use. You type a message, it responds. Write, summarize, brainstorm, answer questions, help you plan.",
            "The free version is excellent. A paid version ($20/month) is more powerful, but the free tier is the perfect place to start.",
          ],
        },
        {
          type: 'tool',
          eyebrow: 'Tool 2',
          icon: '🔷',
          toolName: 'Google Gemini',
          toolMaker: 'by Google',
          toolUrl: 'gemini.google.com',
          body: [
            "Google's conversational AI. Free at gemini.google.com. If you already use Gmail, Google Docs, or Google Drive, Gemini can work directly inside those tools.",
            "Great choice if you're already in the Google world.",
          ],
        },
        {
          type: 'tool',
          eyebrow: 'Tool 3',
          icon: '🪟',
          toolName: 'Microsoft Copilot',
          toolMaker: 'by Microsoft',
          toolUrl: 'copilot.microsoft.com',
          body: [
            "Microsoft's AI, built into Windows, Microsoft 365, Word, Excel, and Outlook.",
            "If your company uses Microsoft products, there's a good chance Copilot is already available to you — sometimes for free. Check with your IT department.",
          ],
        },
        {
          type: 'tool',
          eyebrow: 'Tool 4',
          icon: '🧡',
          toolName: 'Claude',
          toolMaker: 'by Anthropic',
          toolUrl: 'claude.ai',
          body: [
            "Known for being especially thoughtful and excellent at writing tasks. Free to use at claude.ai.",
            "Often described as the best choice for longer, more nuanced writing, analysis, or complex questions. A fantastic alternative to ChatGPT.",
          ],
        },
        {
          type: 'tool',
          eyebrow: 'Tool 5',
          icon: '⚡',
          toolName: 'Grok',
          toolMaker: 'by xAI',
          toolUrl: 'grok.com',
          body: [
            "Elon Musk's AI, built into X (formerly Twitter). Free at grok.com.",
            "Strong at current events and real-time information since it's connected to live data on X. A good option if you're already an X user or want AI that's plugged into what's happening right now.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'The verdict',
          icon: '✅',
          title: 'Which one should you use?',
          body: [
            "<strong>Start with ChatGPT.</strong> It's the most widely used, has the most tutorials and help online, and the free version is very capable.",
            "Once you're comfortable with one, exploring the others takes about five minutes. They're all free to try.",
          ],
          highlight: "Throughout this course, we'll use ChatGPT for our examples. But every exercise works in Gemini, Copilot, Claude, or Grok too — just paste the same prompt.",
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: 'Let AI introduce itself to you.',
          body: ['Open ChatGPT (or whichever tool you chose) and paste this in:'],
          prompt: "I want to learn how to use AI to save time at work. Can you ask me 3 questions to help you understand what I do, so you can suggest the best ways to use AI for my specific job?",
          body2: "Answer its questions honestly. See what it recommends. This is real — and the answers are usually surprisingly specific and useful.",
        },
      ],
    },
    {
      id: 2,
      title: 'What AI Is Actually Good At',
      meta: '10 slides · ~7 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 1 · Lesson 3',
          icon: '⚡',
          title: 'What AI Is Actually Good At',
          body: ["AI has real superpowers. And real limitations. In this lesson you'll get an honest picture of both — so you know exactly when to use it and when to rely on your own judgment."],
          sub: "Let's be straight with each other.",
        },
        {
          type: 'concept',
          eyebrow: 'Superpower 1',
          icon: '✍️',
          title: 'Writing and editing — anything.',
          body: [
            "Emails. Reports. Social posts. Cover letters. Proposals. Thank-you notes.",
            "AI can write a solid first draft of almost anything — in your voice, in any style, at any length. This is probably the #1 time-saver for most working people.",
          ],
          highlight: "You still edit. You still sign off. But the hardest part — the blank page — is gone.",
        },
        {
          type: 'concept',
          eyebrow: 'Superpower 2',
          icon: '📋',
          title: 'Summarizing long things — fast.',
          body: [
            "20-page report? Paste it in, ask for a 1-page summary.",
            "Long email thread? Ask for the key points in 5 bullets.",
            "Messy meeting notes? Ask for a clean action list.",
            "AI is extraordinarily good at condensing large amounts of text into exactly the format you need.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Superpower 3',
          icon: '💡',
          title: 'Brainstorming — on demand.',
          body: [
            "Stuck on a name for something? Need 10 ideas for a social post? Not sure how to handle a tough conversation?",
            "AI can generate options fast. You pick the best ones.",
            "It's like having a brainstorming partner available 24/7 who never gets tired and never runs out of ideas.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Superpower 4',
          icon: '🎯',
          title: 'Answering questions — in <em>your</em> context.',
          body: [
            "Not just generic search results. AI can answer questions about your specific situation.",
            '"I\'m a realtor in Denver writing a blog post for first-time buyers. What should I cover?" It takes your context and tailors its response to you.',
            "That personal relevance is what makes it so useful.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Superpower 5',
          icon: '🧩',
          title: 'Explaining complex things — simply.',
          body: [
            "Medical diagnosis you didn't understand? Legal document full of jargon? Technical instructions that made no sense?",
            "Ask AI to explain it \"like I'm a smart person with no background in this topic.\"",
            "It's remarkably good at translating complicated things into plain English.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Now the honest part',
          icon: '⚠️',
          title: "AI has real limitations. Let's name them.",
          body: ["Knowing the limits is just as important as knowing the strengths. Here's what you need to know."],
          list: {
            items: [
              'It sometimes makes things up — confidently',
              "It doesn't know recent news or events",
              'It can be biased based on what it was trained on',
              "It doesn't know your personal situation unless you tell it",
              "It's not a substitute for professional advice (medical, legal, financial)",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'The most important limitation',
          icon: '🎭',
          title: 'AI sometimes makes things up.',
          body: [
            "This is called <strong>hallucination</strong> — when AI states something confidently that is simply not true. It might invent a statistic, misquote someone, or cite a source that doesn't exist.",
            "It's not lying. It genuinely doesn't know it's wrong. It's just pattern-matching its way to a plausible-sounding answer.",
          ],
          highlight: 'Rule: Never use AI for specific facts, statistics, dates, or quotes without verifying them yourself first.',
        },
        {
          type: 'takeaway',
          eyebrow: 'The Right Mental Model',
          icon: '🙋',
          title: 'Think of AI as a brilliant — but sometimes overconfident — intern.',
          body: [
            '<strong>Brilliant:</strong> Incredibly capable, fast, and genuinely helpful.',
            '<strong>Overconfident:</strong> Will sometimes answer confidently even when wrong.',
            "<strong>Needs supervision:</strong> You're the expert. You review the work. You catch the mistakes.",
          ],
          highlight: 'This mental model will serve you for years. Smart enough to be useful. Human enough to need checking.',
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: 'Map AI to your own work week.',
          body: ['Open ChatGPT and paste this in — filling in the blank with your actual job:'],
          prompt: "I'd like to brainstorm 10 ways I could use AI to save time during my work week. Here's what I do: [describe your job in 2-3 sentences]. Which tasks do you think AI could help me with the most, and how?",
          body2: "Save the list you get back. We'll build on it throughout the course.",
        },
      ],
    },
    {
      id: 3,
      title: 'Your First Real Conversation',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 1 · Lesson 4',
          icon: '💬',
          title: 'Your First Real Conversation',
          body: ["Knowing what AI can do is one thing. Knowing how to talk to it is the skill that unlocks everything. In this lesson, we'll learn a simple formula that makes every AI conversation better — starting today."],
          sub: "This is the lesson people wish they'd learned first.",
        },
        {
          type: 'concept',
          eyebrow: 'The core truth',
          icon: '📥',
          title: 'AI responds to what you give it.',
          body: [
            'Vague question → vague, generic answer.',
            'Specific question → specific, useful, actionable answer.',
            "The skill isn't knowing which buttons to press. The skill is knowing what to ask — and how to ask it.",
          ],
          highlight: 'Better input = better output. Every single time.',
        },
        {
          type: 'concept',
          eyebrow: 'The Simple Formula',
          icon: '🧮',
          title: 'Context + Request + Format',
          body: [
            '<strong>Context:</strong> Who you are and what situation you\'re in.',
            '<strong>Request:</strong> What you want AI to do.',
            '<strong>Format:</strong> How you want the response delivered (short list, paragraph, email, etc.).',
            "You don't need all three every time. But the more you include, the better the result.",
          ],
        },
        {
          type: 'compare',
          eyebrow: "Let's See the Difference",
          title: 'Weak vs. Strong: Side by Side',
          bad: { label: 'Weak Prompt ❌', text: 'Help me write an email.' },
          good: { label: 'Strong Prompt ✅', text: "I'm a sales consultant. I had a great first meeting with a potential client named Sarah last Tuesday. She seemed interested but hasn't replied to my email from 5 days ago. Write a warm, professional follow-up — not pushy — about 3 short paragraphs." },
          highlight: "Same request. Totally different result. That's the power of context.",
        },
        {
          type: 'concept',
          eyebrow: 'Pro Tip 1',
          icon: '🔄',
          title: 'You can always ask for a do-over.',
          body: [
            "If the first response isn't quite right — don't start over. Just continue the conversation:",
            '<strong>"That\'s close, but can you make it shorter?"</strong>',
            '<strong>"Can you make it sound more casual?"</strong>',
            '<strong>"Try that again, but from a different angle."</strong>',
            "AI is patient. It won't be offended. Keep going until it's right.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Pro Tip 2',
          icon: '🎭',
          title: 'Give AI a role to play.',
          body: [
            'Telling AI who to be often dramatically improves its response. Try starting with:',
            '<strong>"Act as a friendly marketing expert..."</strong>',
            '<strong>"You are a patient teacher explaining this to a complete beginner..."</strong>',
            '<strong>"Respond as an experienced HR manager..."</strong>',
            'Framing the role gives AI a helpful filter to respond through.',
          ],
        },
        {
          type: 'exercise',
          eyebrow: 'Build a Prompt Together',
          icon: '🔨',
          title: 'Fill in the blanks to build your prompt.',
          body: ["Here's a universal prompt template. Fill in the highlighted parts:"],
          template: true,
          templateText: 'I am a [FILL IN: your job or role]. I need to [FILL IN: what you want to accomplish]. The person I am communicating with is [FILL IN: describe them]. Please [write / create / suggest / explain] this in a [FILL IN: professional / friendly / casual] tone. Keep it [FILL IN: short and direct / under 150 words / detailed].',
          body2: "Take your completed version and paste it into ChatGPT. This one template will serve you for years.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Key Takeaway',
          icon: '✨',
          title: 'The conversation is the skill.',
          body: [
            "AI is a conversation partner, not a search engine. The more you practice talking to it clearly and specifically, the more useful it becomes.",
            "Think of it like learning to work with a new colleague. At first you over-explain everything. Then you develop a shorthand. Then it gets effortless.",
          ],
          highlight: 'Every conversation makes you better. Start talking.',
        },
      ],
    },
    {
      id: 4,
      title: 'Thinking Clearly About AI',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 1 · Lesson 5',
          icon: '🧭',
          title: 'Thinking Clearly About AI',
          body: ["This is the lesson that separates confident AI users from people who get misled or disappointed. In this final lesson of Module 1, we'll cover how to stay sharp, safe, and always in control."],
          sub: 'Confidence comes from knowing both sides.',
        },
        {
          type: 'concept',
          eyebrow: 'The most important mindset',
          icon: '👤',
          title: 'AI is a tool. You are the expert.',
          body: [
            "This might sound obvious, but it matters more than anything else: AI helps you. <em>You lead.</em>",
            "AI knows a lot about many things. You know about your specific situation, your relationships, your values, and your judgment. Never hand that over.",
            "Use AI as a very capable assistant — not a final authority.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Understanding Hallucination',
          icon: '🔍',
          title: 'Why AI makes things up — and what to do about it.',
          body: [
            "Remember: AI is predicting what a helpful answer looks like based on patterns. Sometimes those patterns lead it to generate something that sounds true — but isn't.",
            "It's not lying. It genuinely doesn't know it's wrong. This is a fundamental feature of how the technology works.",
          ],
          highlight: 'Rule of thumb: Use AI for drafts, ideas, and explanations. Verify specific facts, statistics, names, dates, and quotes before sharing or acting on them.',
        },
        {
          type: 'concept',
          eyebrow: 'Your Privacy',
          icon: '🔒',
          title: "What you share with AI — know the basics.",
          body: [
            "Different tools have different privacy policies. Here's general guidance:",
            '<strong>Low risk:</strong> Writing help, summaries, brainstorming, general questions.',
            '<strong>Use caution:</strong> Detailed company strategy, confidential client information, legal matters.',
            '<strong>Avoid entirely:</strong> Social Security numbers, financial account details, passwords.',
            "For most everyday work tasks, AI tools are safe to use. When in doubt, use common sense.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'The bigger picture',
          icon: '💼',
          title: 'Will AI replace my job?',
          body: [
            "Honest answer: some tasks will change. Most jobs will evolve, not disappear — especially in the near term.",
            "The bigger truth: people who use AI well will be more productive and more valuable than those who don't. You're not competing with AI.",
            "You're competing with other people. The ones using AI have a real advantage.",
          ],
          highlight: "AI won't replace you. Someone using AI effectively might. That's exactly why you're here.",
        },
        {
          type: 'concept',
          eyebrow: 'The Healthy Mindset',
          icon: '🌱',
          title: 'Stay curious. Stay skeptical. Stay in charge.',
          body: [
            '<strong>Curious:</strong> Explore. Try new things. Ask weird questions. AI rewards experimentation.',
            "<strong>Skeptical:</strong> Check important things. Don't take everything at face value.",
            "<strong>In charge:</strong> You decide what to use, what to share, and when to trust it.",
            "That's not limiting — that's exactly how it should work.",
          ],
        },
        {
          type: 'takeaway',
          eyebrow: 'Module 1 Complete! 🎉',
          icon: '🏆',
          title: "Look how far you've come.",
          body: ["In this module, you've learned:"],
          summaryList: [
            "What AI actually is — and what it isn't",
            'The main tools and how they compare',
            "What AI is genuinely great at — and its real limitations",
            'How to have a productive, specific conversation with AI',
            'How to stay sharp, safe, and in control',
          ],
        },
        {
          type: 'exercise',
          eyebrow: 'Final Exercise Before the Quiz',
          icon: '🎯',
          title: 'One more real practice.',
          body: ['Open ChatGPT and paste this in:'],
          prompt: "I just finished learning the basics of AI. Based on what you know about me (or if we haven't talked — I'll describe my job briefly), what's the single most impactful way I could use AI this week? Give me step-by-step instructions as if I've never done this before.",
          body2: "Then take the Module 1 quiz below. You're ready — I promise.",
        },
      ],
    },
  ],
  quiz: [
    {
      q: 'What is the most accurate way to describe how AI works?',
      options: [
        'It thinks and feels like a human brain',
        'It matches patterns learned from enormous amounts of training data',
        'It searches the internet in real time to find answers',
        'It makes educated random guesses',
      ],
      correct: 1,
      feedback: "Correct! AI learns patterns from huge amounts of text and data, then uses those patterns to respond to your input. It doesn't think like a human — it pattern-matches at incredible speed.",
    },
    {
      q: 'Which of the following is AI genuinely great at?',
      options: [
        'Telling you what happened in the news yesterday',
        'Giving you guaranteed, 100% accurate facts',
        'Drafting emails, summarizing documents, and brainstorming ideas',
        'Making final business decisions for you',
      ],
      correct: 2,
      feedback: "Exactly right. Writing, summarizing, and brainstorming are AI's true superpowers. Always verify specific facts, and never outsource your final judgment.",
    },
    {
      q: "What is 'hallucination' in the context of AI?",
      options: [
        'When AI crashes or stops working',
        'When AI responds very slowly',
        "When AI confidently states something that isn't true",
        'When AI refuses to answer a question',
      ],
      correct: 2,
      feedback: "Yes. Hallucination is when AI generates false information in a confident, convincing way. It's not lying — it simply doesn't know it's wrong. This is why you verify important facts.",
    },
    {
      q: 'Which is the stronger, more useful prompt?',
      options: [
        '"Write me an email."',
        '"Help me with something at work."',
        '"I\'m a project manager. Write a professional but friendly follow-up to my client who hasn\'t responded in a week. Keep it under 100 words."',
        '"Email. Client. Follow-up. Short."',
      ],
      correct: 2,
      feedback: "Correct. Context + specific request + format = much better result. The more specific you are, the more useful the output. Practice this and it becomes second nature.",
    },
    {
      q: 'What is the best mindset for working with AI?',
      options: [
        'Trust it completely — it usually knows more than I do',
        "Avoid it until it's more reliable and accurate",
        'Use it as a capable tool, stay curious, and verify important facts',
        "Only use it for very simple tasks where mistakes don't matter",
      ],
      correct: 2,
      feedback: "Exactly. Curious + skeptical + in charge. Use AI as a powerful assistant, not an oracle. Review its work, verify important things, and let it handle the heavy lifting on drafts and ideas.",
    },
  ],
}

export default module1
