import type { CourseData } from './types'

const module2: CourseData = {
  moduleId: 2,
  title: 'ChatGPT & Your Work: Getting Things Done',
  subtitle: 'ChatGPT & Your Work',
  nextModuleId: 3,
  lessons: [
    {
      id: 0,
      title: 'Getting Started with ChatGPT',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 2 · Lesson 1',
          icon: '🚀',
          title: "Let's actually use this thing.",
          body: ["In Module 1, you learned what AI is. Now it's time to use it — on real tasks, for real results. By the end of this module, you'll have a workflow you can use every single day."],
          sub: 'Starting with the basics: ChatGPT, from the very first screen.',
        },
        {
          type: 'concept',
          eyebrow: "The tool we'll use",
          icon: '🤖',
          title: "We're using ChatGPT — and here's why.",
          body: [
            "There are several great AI tools. We're using ChatGPT because it's the most widely used, the free version is excellent, and there's more help and guidance available for it than any other tool.",
            "Everything you learn here works the same way in Google Gemini, Microsoft Copilot, or Claude. Once you know how to use one, the others take about 10 minutes to figure out.",
          ],
          highlight: "You're not locked in. You're building a skill that works everywhere.",
        },
        {
          type: 'concept',
          eyebrow: 'The interface',
          icon: '💻',
          title: 'The whole thing is one text box.',
          body: [
            "When you open ChatGPT, you'll see a mostly empty screen with a text box at the bottom. That's it.",
            "You type something in. ChatGPT responds. You reply back. That's the entire interface.",
            "There's nothing to configure, no settings to learn first, no manual to read. It's a conversation — and you already know how to have a conversation.",
          ],
        },
        {
          type: 'concept',
          eyebrow: 'How it works',
          icon: '🔄',
          title: 'Think of it as a very capable back-and-forth.',
          body: [
            '<strong>You type a message.</strong> This is called a "prompt." It can be a question, a request, a piece of text you want help with — anything.',
            '<strong>ChatGPT responds.</strong> Usually in seconds. Sometimes impressively well. Sometimes not quite right.',
            "<strong>You reply.</strong> If the first response wasn't what you needed, you tell it. It tries again. This back-and-forth is where the real magic happens.",
          ],
          highlight: "The back-and-forth is the skill. Most people type once, read the response, and give up. We'll do better than that.",
        },
        {
          type: 'concept',
          eyebrow: 'One important thing to know',
          icon: '🧠',
          title: 'It remembers — but only within the conversation.',
          body: [
            "Within a single conversation, ChatGPT remembers everything you've said. You can refer back to earlier things: \"Make that email shorter\" or \"Apply the same tone to this one.\"",
            'But when you start a <strong>new conversation</strong>, it starts fresh. It has no memory of your previous chats.',
            "This is actually useful — you can start clean whenever you want. And it means you should give it context at the start of each new conversation.",
          ],
        },
        {
          type: 'tool',
          eyebrow: 'Your tool',
          icon: '🤖',
          toolName: 'ChatGPT',
          toolMaker: 'by OpenAI',
          toolUrl: 'chatgpt.com',
          body: [
            "Free to use at chatgpt.com. No download needed — it runs in your browser.",
            "<strong>Free tier:</strong> More than enough for everything in this course. Write, ask, brainstorm, summarize — all free.",
            "<strong>Paid tier (ChatGPT Plus, $20/month):</strong> Faster, more powerful. Worth it if you use it daily, but not necessary to start.",
          ],
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: 'Start your first work-focused conversation.',
          body: ['Open <strong>chatgpt.com</strong> in a new tab and paste this in. Fill in the blank with your actual job.'],
          prompt: "I'm going to be using you to help with my work. Here's what I do: [describe your job in 2-3 sentences]. Over the next few weeks I'd like to use you to save time on tasks like writing, summarizing, and organizing information. To start — what are the top 3 ways you think you could help someone in my role?",
          body2: "Read what it says. It will ask follow-up questions or give you a specific, useful list. Either way — you've just started a real work conversation with AI.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 1 Complete',
          icon: '✅',
          title: "You're oriented. Now let's get good at this.",
          body: [
            "You know what ChatGPT looks like, how it works, and how to start a real conversation with it.",
            "In the next lesson, we get into the skill that makes everything else better: how to write a prompt that actually gets you what you want.",
          ],
          summaryList: [
            "ChatGPT is a text-based conversation — no setup, no configuration",
            "It remembers your conversation but starts fresh each new chat",
            "You give it context, it responds, you refine — that's the whole game",
            "The free version is all you need for this entire course",
          ],
        },
      ],
    },
    {
      id: 1,
      title: 'The Art of the Prompt',
      meta: '9 slides · ~7 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 2 · Lesson 2',
          icon: '✍️',
          title: 'One skill separates good results from great ones.',
          body: ["Most people type one vague sentence and wonder why the results feel generic. The fix is simple — and once you learn it, you'll use it every single time."],
          sub: "It's called a prompt. And there's a formula.",
        },
        {
          type: 'compare',
          eyebrow: 'Spot the difference',
          title: 'Same tool. Completely different results.',
          body: ["Here's why vague prompts get vague answers — and how one extra sentence changes everything."],
          bad: { label: '❌ Weak prompt', text: 'Write me an email.' },
          good: { label: '✅ Strong prompt', text: "I'm a project manager. Write a friendly but professional follow-up email to a client who hasn't responded in a week. Keep it under 80 words. Don't sound pushy." },
          highlight: "ChatGPT is trying to help you. But it can only work with what you give it. Give it more — get more back.",
        },
        {
          type: 'concept',
          eyebrow: 'The formula',
          icon: '📐',
          title: 'Every great prompt has three parts.',
          body: ["You don't have to memorize rules. You just have to include three things: who you are, what you want, and how you want it."],
          list: {
            items: [
              '<strong>Context</strong> — Who are you? What\'s the situation? Give it background.',
              '<strong>Request</strong> — What specifically do you want it to do?',
              '<strong>Format</strong> — How long? What tone? What structure?',
            ],
            negative: false,
          },
          highlight: "Context + Request + Format. You don't need all three every time — but the more you include, the better the response.",
        },
        {
          type: 'concept',
          eyebrow: 'Part 1 of 3',
          icon: '👤',
          title: '<em>Context:</em> Tell it who you are and what\'s going on.',
          body: [
            "ChatGPT doesn't know anything about you unless you tell it. The more relevant context you share, the more tailored its response will be.",
            "Good context looks like: your job, your audience, the situation, the tone you need, any constraints.",
          ],
          list: {
            items: [
              '"I\'m a small business owner who runs a pet grooming shop..."',
              '"I\'m writing to a client who\'s frustrated about a delay..."',
              '"This is for my company newsletter — our audience is nurses..."',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Part 2 of 3',
          icon: '🎯',
          title: '<em>Request:</em> Be specific about exactly what you want.',
          body: [
            '"Help me" is too vague. "Write a 3-sentence apology to a customer whose order arrived late" is specific.',
            'The more precisely you describe the task, the more useful the output.',
          ],
          list: {
            items: [
              '"Summarize this in 5 bullet points"',
              '"Write 3 options for a subject line for this email"',
              '"Rewrite this paragraph to sound warmer and less corporate"',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Part 3 of 3',
          icon: '📋',
          title: '<em>Format:</em> Tell it how you want the response.',
          body: [
            "AI will give you a long paragraph unless you tell it otherwise. If you want bullets, a table, a short answer, or a specific length — just say so.",
            "Format instructions are easy and make a huge difference.",
          ],
          list: {
            items: [
              '"Keep it under 100 words"',
              '"Format this as a numbered list"',
              '"Write it in a casual, conversational tone"',
              '"Give me three different versions to choose from"',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Putting it together',
          icon: '🔧',
          title: 'The formula in action.',
          body: ["Here's the same request — built with and without the formula:"],
          list: {
            items: [
              '"Write a LinkedIn post about my business."',
              '"I own a bookkeeping firm that helps small restaurants. Write a LinkedIn post announcing that I\'m taking on 3 new clients this month. Keep it under 150 words. Sound confident but approachable — not salesy."',
            ],
            negative: false,
          },
          highlight: "You don't need to be perfect. Even one extra sentence of context makes a meaningful difference.",
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: 'Build a prompt using the formula.',
          body: ['Think of something you actually need to write this week — an email, a message, a summary. Open ChatGPT and write a prompt using <strong>Context + Request + Format</strong>. Or use this fill-in template:'],
          prompt: "I'm a [your job]. I need to [specific task]. The audience is [who will read it]. Please [format instruction — e.g., keep it under 100 words / write 3 options / use bullet points].",
          body2: "Try it once with the formula, then once without. Notice the difference in what you get back.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 2 Complete',
          icon: '✅',
          title: 'You now have the single most useful AI skill there is.',
          body: ["The prompt formula works for everything — writing, summarizing, brainstorming, explaining, analyzing. Every lesson from here builds on it."],
          summaryList: [
            "Vague prompts get vague answers — specificity is everything",
            "Context + Request + Format is the formula for great results",
            "You don't need all three every time — but more context always helps",
            "You can use this immediately on any real task",
          ],
          template: true,
          templateText: "I'm a [your job]. I need to [specific task]. The audience is [who will read or hear it]. Please [format: length / tone / structure].",
        },
      ],
    },
    {
      id: 2,
      title: 'Your Top 5 Work Tasks',
      meta: '9 slides · ~7 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 2 · Lesson 3',
          icon: '⚡',
          title: 'Five tasks. Immediate results.',
          body: [
            "You don't have to figure out how AI fits into your work — we'll show you exactly where it saves the most time, for most people, most of the time.",
            "These five tasks cover about 80% of what working adults use AI for. Pick the ones that match your life.",
          ],
          sub: "Let's make this practical right now.",
        },
        {
          type: 'concept',
          eyebrow: 'Task 1 of 5',
          icon: '📧',
          title: 'Writing and editing — your biggest time-saver.',
          body: [
            "Emails. Reports. Proposals. Social posts. Announcements. Performance reviews. AI can write a solid first draft of almost any professional document in seconds.",
            "You still review it. You still add your personality. But the blank page — the hardest part — is gone.",
          ],
          highlight: "The average professional spends 28% of their workweek on email alone. Even cutting that in half is worth it.",
        },
        {
          type: 'concept',
          eyebrow: 'Task 2 of 5',
          icon: '📄',
          title: 'Summarizing — turn a wall of text into something useful.',
          body: [
            "Paste in a long document, a meeting transcript, a chain of emails, or a report. Ask for the key points, a one-paragraph summary, or a list of action items.",
            "AI is extraordinarily good at this — it can turn 20 pages into 5 bullets in about 10 seconds.",
          ],
          list: {
            items: [
              '"Summarize this in 3 sentences"',
              '"Pull out all the action items from this meeting transcript"',
              '"What are the 5 most important points in this report?"',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Task 3 of 5',
          icon: '💡',
          title: 'Brainstorming — on demand, 24/7.',
          body: [
            "Stuck on a name? Need ideas for a social post? Can't figure out how to start a difficult conversation? AI generates options fast.",
            "You pick the best ideas. You don't have to use them as-is. But having 10 starting points is infinitely better than staring at a blank page.",
          ],
          highlight: 'Ask for more than you need. "Give me 15 ideas" is better than "Give me 5." You\'ll probably use 2 of them — and that\'s fine.',
        },
        {
          type: 'concept',
          eyebrow: 'Task 4 of 5',
          icon: '🙋',
          title: 'Answering questions — in <em>your</em> context.',
          body: [
            "Unlike Google, AI doesn't give you a list of links. It answers your actual question — and you can give it your specific situation to get a tailored response.",
            '"I\'m a dental hygienist asking a nervous patient about flossing. How should I phrase this?" It\'ll give you a thoughtful, specific answer, not a generic article.',
          ],
        },
        {
          type: 'concept',
          eyebrow: 'Task 5 of 5',
          icon: '🔍',
          title: 'Explaining complex things — in plain English.',
          body: [
            "Got a legal document full of jargon? A medical term you don't understand? A technical report that reads like a foreign language?",
            'Paste it in and ask: "Explain this like I\'m a smart person with no background in this topic." The results are usually remarkably clear.',
          ],
          highlight: "This one is a game-changer for anyone who regularly has to read things outside their area of expertise.",
        },
        {
          type: 'compare',
          eyebrow: 'Time in practice',
          title: 'What this actually looks like in a workday.',
          body: ["Here's a real before-and-after for a single task that most professionals do regularly:"],
          bad: { label: '⏱️ Without AI — 35 minutes', text: 'Stare at blank document. Start and delete three times. Draft a 400-word project update email. Reread it five times. Send.' },
          good: { label: '⚡ With AI — 8 minutes', text: 'Paste in your bullet points. Ask for a professional update email under 200 words. Read the draft. Make two small edits. Send.' },
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: "Draft something you've been putting off.",
          body: [
            "Think of one thing in your work to-do list that involves writing. An email you've been avoiding. A message you need to send. A summary you need to produce.",
            "Open ChatGPT and use the prompt formula from Lesson 2 to get a first draft. Use your real context, your real task.",
          ],
          prompt: "I'm a [your job]. I need to write [describe the specific thing — email, summary, announcement, etc.]. Here's the key information: [paste your notes or bullet points]. Please write a draft that is [tone: professional/friendly/direct] and [length: under X words / about X paragraphs].",
          body2: "You're not committing to using exactly what it writes. You're getting a starting point. That alone saves most of the time.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 3 Complete',
          icon: '✅',
          title: 'You have a practical AI toolkit for your work week.',
          body: [
            "These five tasks — writing, summarizing, brainstorming, answering questions, and explaining things — cover most of what working adults use AI for every day.",
            "In the next lesson, we learn how to take a good first draft and make it great.",
          ],
          summaryList: [
            "Writing & editing: first drafts in seconds, you polish",
            "Summarizing: turn any long document into exactly what you need",
            "Brainstorming: generate 10 ideas and pick the 2 that work",
            "Q&A in context: answers tailored to your specific situation",
            "Explaining jargon: plain English on demand",
          ],
        },
      ],
    },
    {
      id: 3,
      title: 'The Back-and-Forth',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 2 · Lesson 4',
          icon: '🔄',
          title: 'One message is almost never enough.',
          body: [
            "Most people type a prompt, read the response, decide it's not quite right, and give up. That's the single biggest mistake people make with AI.",
            "The first response is just the beginning of the conversation. The real results come from going back and forth.",
          ],
          sub: 'This lesson teaches you how to get from good to great — in 2–3 rounds.',
        },
        {
          type: 'concept',
          eyebrow: 'The key insight',
          icon: '🎯',
          title: 'AI is working with you, not for you once.',
          body: [
            "Think of the first response as a draft — exactly like a first draft from a human colleague. It might be 80% of the way there. Your job is to give feedback.",
            "You don't need to rewrite your prompt from scratch. You just reply with what needs to change.",
          ],
          highlight: '"Make it shorter." "Too formal — try again." "Add a line about the deadline." These simple replies change everything.',
        },
        {
          type: 'concept',
          eyebrow: 'The phrases that work',
          icon: '💬',
          title: "You don't need special language. Everyday English works.",
          body: ["You can talk to ChatGPT exactly like you'd talk to a helpful colleague. Here are the phrases most people find themselves using constantly:"],
          list: {
            items: [
              '"Make this shorter — about half as long"',
              '"This is too formal. Rewrite it in a warmer, more casual tone"',
              '"Add a sentence about [specific thing]"',
              '"Can you give me 3 different versions of this?"',
              '"The middle part is good — keep that, but change the opening"',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Pasting content in',
          icon: '📋',
          title: 'You can give it real material to work with.',
          body: [
            "ChatGPT works best when you give it actual content — not just a description of it.",
            "Paste in a document, an email thread, a set of notes, or a rough draft. Then tell it what to do with it.",
          ],
          list: {
            items: [
              '"Here are my rough notes. Turn them into a polished summary."',
              '"Here\'s a long email thread. What are the three key decisions we need to make?"',
              '"Here\'s my draft. Make it cleaner — fix grammar and tighten the language."',
            ],
            negative: false,
          },
        },
        {
          type: 'compare',
          eyebrow: 'Side by side',
          title: 'One shot vs. two rounds.',
          body: ['Same task — see what an extra round of feedback does:'],
          bad: { label: '🔴 One-shot result', text: "Here's the email I wrote for you. I hope it's helpful and meets your needs for the situation you described above regarding the follow-up message." },
          good: { label: '✅ After one round of feedback', text: "Hi Sarah — just checking in on the proposal I sent last Tuesday. Happy to jump on a quick call if you have questions. Let me know what works!" },
        },
        {
          type: 'concept',
          eyebrow: 'Your follow-up toolkit',
          icon: '🛠️',
          title: "Save these — you'll use them every day.",
          body: ["These follow-up prompts work across almost every type of task:"],
          list: {
            items: [
              '<strong>Tone:</strong> "Make this sound more [friendly / direct / professional / conversational]"',
              '<strong>Length:</strong> "Shorten this to under [X] words" or "Expand the second paragraph"',
              '<strong>Options:</strong> "Give me 3 different versions of the subject line"',
              '<strong>Focus:</strong> "Remove the part about X and emphasize Y instead"',
              '<strong>Regenerate:</strong> "Try again" (it\'ll take a different approach entirely)',
            ],
            negative: false,
          },
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: 'Take your Lesson 3 draft and make it better in two rounds.',
          body: [
            "Go back to the email or document you drafted in Lesson 3. Or create a new draft now. Once ChatGPT gives you the first response — don't stop there.",
            "Round 1: Reply with one specific change (tone, length, add something).",
            "Round 2: Reply with one more adjustment.",
          ],
          prompt: "Here's what you gave me: [paste the draft]. I like the overall approach but I'd like you to: [one specific change — shorter / warmer / add a line about X / give me 3 options for the subject line].",
          body2: "Two rounds of feedback usually gets you to something you'd actually send. That's the skill.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 4 Complete',
          icon: '✅',
          title: "Iteration is the real skill. You've got it.",
          body: [
            "The back-and-forth is what separates people who use AI occasionally from people who use it effectively every day.",
            "One more lesson left — and it's about making all of this a natural part of how you work.",
          ],
          summaryList: [
            "Treat the first response as a draft, not a final answer",
            "Simple follow-ups — shorter, warmer, add X — work perfectly well",
            "Paste in real content and tell it what to do with it",
            "Two rounds of feedback usually gets you to something you can use",
          ],
        },
      ],
    },
    {
      id: 4,
      title: 'Making It Stick',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 2 · Lesson 5',
          icon: '🌱',
          title: 'The gap between "trying it once" and actually using it.',
          body: [
            "Most people try AI once or twice, get a mixed result, and forget about it for six months. Then they see a colleague using it daily and wonder what they're missing.",
            "This lesson is about closing that gap — building a simple, sustainable habit that makes AI a natural part of your workday.",
          ],
          sub: "It takes about 10 days of small steps. Let's set you up right.",
        },
        {
          type: 'concept',
          eyebrow: 'The mindset shift',
          icon: '🧠',
          title: 'Start with the draft, not the blank page.',
          body: [
            "The single most powerful habit is this: whenever you need to write something, ask ChatGPT for a first draft <em>before</em> you start writing.",
            "Even if you rewrite 90% of it, you'll finish faster — because rewriting is easier than creating from nothing.",
            'This is the "AI first draft" mindset. It takes about two weeks to make it automatic.',
          ],
          highlight: "The blank page is the enemy. AI eliminates the blank page.",
        },
        {
          type: 'concept',
          eyebrow: 'Three daily habits',
          icon: '📅',
          title: 'Under 5 minutes each. Pick one to start.',
          body: ["You don't need to overhaul your workflow. Just pick one of these and do it every day for two weeks:"],
          list: {
            items: [
              "<strong>The morning email habit:</strong> Any email that takes more than 5 minutes to write — draft it with AI first",
              "<strong>The end-of-day summary habit:</strong> Paste your notes from the day and ask for a clean summary or action list",
              "<strong>The \"I don't know where to start\" habit:</strong> When you're stuck on anything — ask AI for a starting point or 5 ideas",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Knowing the limits',
          icon: '⚠️',
          title: 'When <em>not</em> to use AI — and why this matters.',
          body: ["Using AI well also means knowing when not to use it. Being clear-eyed about this actually builds your confidence."],
          list: {
            items: [
              "<strong>Sensitive conversations</strong> — performance reviews, firings, personal apologies deserve your own words",
              "<strong>Facts and statistics</strong> — always verify; AI can hallucinate convincing-sounding data",
              "<strong>Medical, legal, or financial decisions</strong> — AI is not a licensed professional",
              "<strong>Anything you haven't reviewed</strong> — never send AI output without reading it yourself first",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Your prompt library',
          icon: '📚',
          title: 'Save the prompts that work for you.',
          body: [
            "Once you find a prompt that gets you great results for a recurring task — save it. Keep a running document (a Google Doc, a Notes file, anything) with your go-to prompts.",
            "Over time you'll build a personal prompt library that makes every repeat task faster and faster.",
          ],
          list: {
            items: [
              "Weekly team update template",
              "Customer response to a complaint",
              "Meeting agenda from bullet points",
              "Performance review talking points",
            ],
            negative: false,
          },
        },
        {
          type: 'compare',
          eyebrow: 'A realistic week',
          title: 'Before AI vs. after two weeks of practice.',
          body: ["Here's what a real workweek can look like — once the habit is in place:"],
          bad: { label: '📅 Before AI', text: 'Monday: 45 min on weekly update. Wednesday: 30 min on a client email. Friday: an hour writing a proposal outline. Total: ~2.5 hrs on writing tasks.' },
          good: { label: '⚡ After 2 weeks of practice', text: 'Monday: 12 min on weekly update. Wednesday: 8 min on client email. Friday: 20 min on proposal outline. Total: ~40 min. Saved nearly 2 hours.' },
        },
        {
          type: 'exercise',
          eyebrow: 'Try This Right Now',
          icon: '🎯',
          title: 'Write your first saved prompt.',
          body: [
            "Think of a writing task you do regularly at work — at least once a week. Something that always takes longer than it should.",
            "Open ChatGPT and write a prompt for that exact task — with full context and format instructions. Run it. Refine it until the result is something you'd actually use.",
            "Then copy that prompt into a document somewhere. Label it. That's the start of your prompt library.",
          ],
          prompt: "I'm a [your job]. I regularly need to [describe the recurring task]. The audience is usually [who reads it]. The result should be [tone: professional/casual/direct] and [length/format]. Here's a specific example to work from: [paste a real example if you have one, or describe a typical case].",
          body2: "A prompt library of even 5 well-crafted templates can save you hours a week. Start with one.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Module 2 Complete',
          icon: '🎉',
          title: "You're not just learning about AI — you're using it.",
          body: [
            "You've completed Module 2. You know how ChatGPT works, how to write prompts that get real results, how to use AI for your five most common work tasks, how to refine the output — and how to build a habit that sticks.",
            "In Module 3, we go deeper: how to use AI for research, planning, and decision-making. You're ready.",
          ],
          summaryList: [
            'The "AI first draft" mindset eliminates the blank page',
            "Pick one small daily habit and do it for two weeks",
            "Know when not to use AI — that's wisdom, not weakness",
            "Build a prompt library for your recurring tasks",
            "You've got the foundation — everything from here builds on it",
          ],
        },
      ],
    },
  ],
  quiz: [
    {
      q: "What's the most important thing to include in a ChatGPT prompt to get a better result?",
      options: [
        "Keep it as short and simple as possible",
        "Use technical language so it takes the task seriously",
        "Give it context — who you are, what you need, and how you want it formatted",
        "Always start with 'Please' to be polite",
      ],
      correct: 2,
      feedback: "Context is everything. The more relevant information you give it — your role, the task, the audience, the format — the more tailored and useful the response. Vague prompts get vague answers.",
    },
    {
      q: "ChatGPT's first response isn't quite right. What should you do?",
      options: [
        "Start over with a completely new conversation",
        "Accept it — AI usually knows best",
        "Switch to a different AI tool",
        "Reply with specific feedback — 'Make it shorter' or 'Try a warmer tone'",
      ],
      correct: 3,
      feedback: "The back-and-forth is the skill. Reply with one clear piece of feedback and it'll try again. Most good results come after 2–3 rounds of refinement, not on the first try.",
    },
    {
      q: "Which of these is the strongest prompt?",
      options: [
        '"Write me an email."',
        '"Email for work thing — keep it short."',
        '"I\'m a nurse manager. Write a brief, warm message to my team reminding them about Monday\'s huddle. Keep it under 60 words and sound human, not corporate."',
        '"Something about a Monday meeting."',
      ],
      correct: 2,
      feedback: "Correct. Context (nurse manager), Request (team reminder about Monday's huddle), Format (under 60 words, warm tone). The formula works every time — the more specific, the better the output.",
    },
    {
      q: "ChatGPT remembers everything you've told it across all your conversations. True or false?",
      options: [
        "True — it builds a detailed profile of you over time",
        "False — it only remembers within the current conversation (by default)",
        "True — it stores everything permanently in your account",
        "False — it forgets everything after every single message",
      ],
      correct: 1,
      feedback: "By default, ChatGPT remembers within the current conversation but starts fresh each new chat. This means you should give it relevant context at the start of each new conversation — don't assume it knows your situation.",
    },
    {
      q: "What's the best description of how AI should fit into your work?",
      options: [
        "Replace your own judgment — it usually knows more than you do",
        "Use it for first drafts, brainstorming, and summarizing — then you review and finalize",
        "Only use it for very simple tasks where mistakes won't matter",
        "Trust its facts and statistics — it has access to the whole internet",
      ],
      correct: 1,
      feedback: "AI is a powerful starting point, not a replacement for your judgment. It handles the heavy lifting on drafts and ideas — you bring the expertise, the review, and the final decision. That partnership is where the real value is.",
    },
  ],
}

export default module2
