import type { CourseData } from './types'

const module6: CourseData = {
  moduleId: 6,
  title: 'Your AI Life — Staying Current and Going Further',
  subtitle: 'Your AI Life',
  lessons: [
    {
      id: 0,
      title: "What You've Built",
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 6 · Lesson 1',
          icon: '🏆',
          title: "Look how far you've come.",
          body: [
            "Six modules ago, AI was something you heard about but weren't sure how to use — or whether it was even for someone like you.",
            "That's changed. Before we look forward, let's take a minute to look back and actually see what you've built.",
          ],
          sub: "This lesson is about recognizing what you've learned — and why it matters.",
        },
        {
          type: 'concept',
          eyebrow: 'Before vs. after',
          icon: '↔️',
          title: "You're a different kind of person now than when you started.",
          body: ["Compare where you were at the start of Module 1 to where you are right now:"],
          beforeAfter: {
            before: {
              label: 'Before Clearly, AI',
              items: [
                'Unsure what AI actually is',
                'Never used ChatGPT',
                'Worried about looking dumb',
                'Felt left behind',
                'No idea where to start',
              ],
            },
            after: {
              label: 'After 6 Modules',
              items: [
                'You understand how AI works',
                'You use it for real work tasks',
                'You can evaluate new tools confidently',
                'You have a personal AI stack',
                'You know how to keep learning',
              ],
            },
          },
        },
        {
          type: 'concept',
          eyebrow: 'Your actual skills',
          icon: '🧠',
          title: "Here's what you can actually do now.",
          body: ["This isn't abstract. These are real, specific skills you've practiced:"],
          list: {
            items: [
              'Write effective prompts using Context + Request + Format',
              'Use ChatGPT to draft, summarize, edit, brainstorm, and research',
              'Generate custom images from a written description',
              'Transcribe meetings automatically with Otter.ai',
              'Find AI tools built for your specific job or industry',
              'Create a content system — posts, emails, scripts — with AI assistance',
              'Evaluate any new AI tool with a 3-question test',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'The real shift',
          icon: '💡',
          title: "The biggest change isn't the tools. It's the mindset.",
          body: [
            "The skills above are valuable. But the more important thing you've built is harder to put on a list.",
            "You now think about AI differently. When you face a task — a hard email to write, a report to summarize, a problem to think through — your first instinct is to ask: <strong>could AI help with this?</strong> That question, asked habitually, is worth more than any single tool.",
          ],
          highlight: 'AI-first thinking is the skill that compounds over time.',
        },
        {
          type: 'concept',
          eyebrow: 'What it looks like',
          icon: '📅',
          title: 'A week in the life of someone who uses AI.',
          body: ["Here's what your week might start to look like — not dramatically, but meaningfully different:"],
          list: {
            items: [
              '<strong>Monday:</strong> Use ChatGPT to prep for a difficult meeting — anticipated questions, talking points.',
              '<strong>Tuesday:</strong> Let Otter transcribe and summarize the meeting. Share action items in 3 minutes.',
              '<strong>Wednesday:</strong> Draft a proposal with ChatGPT as a first pass. Edit it to sound like you.',
              '<strong>Thursday:</strong> Use Perplexity to research a topic. Get cited sources instead of 10 browser tabs.',
              "<strong>Friday:</strong> Create a LinkedIn post from the week's work in under 5 minutes.",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: "You're ahead",
          icon: '🚀',
          title: "Most people still haven't done what you just did.",
          body: [
            "It sounds simple, but it's true: most adults who have heard about AI have never actually sat down, learned it systematically, and practiced it with real tasks.",
            "You have. That puts you in a small group — not because you're a tech person, but because you decided to spend the time. That matters.",
          ],
          highlight: "You didn't just learn about AI. You started using it. That's the whole game.",
        },
        {
          type: 'exercise',
          eyebrow: 'Reflect',
          icon: '✍️',
          title: 'Write your own before and after.',
          body: ["Before moving on, take 3 minutes to write your own version of the before/after. Make it specific to you."],
          prompt: "Open a note or doc and write:\n\nBefore Clearly, AI, I used to...\n[2–3 specific things you didn't know or couldn't do]\n\nNow I can...\n[2–3 specific things you know or have actually done]\n\nThe one thing I want to use AI for more is...\n[name it specifically]\n\nSave this. You'll want it in a few months when you forget how much you've learned.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 1 complete',
          icon: '✅',
          title: "You've earned a moment to recognize what you've built.",
          summaryList: [
            "You have real, specific AI skills — not just awareness, but practice.",
            "The biggest change is your mindset: you now think AI-first when facing tasks.",
            "You're ahead of most people — not because you're technical, but because you showed up.",
            "You've written your own before/after to make that concrete.",
          ],
        },
      ],
    },
    {
      id: 1,
      title: 'Thinking Critically About AI',
      meta: '9 slides · ~7 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 6 · Lesson 2',
          icon: '🧭',
          title: 'Using AI well means knowing what to <em>trust</em> — and what to check.',
          body: [
            "The biggest risk with AI isn't that people won't use it — it's that people will trust it too much. AI is powerful, but it makes mistakes. Confident, well-written, completely wrong mistakes.",
            "This lesson teaches you how to use AI smartly: getting all the value while staying sharp about its limits.",
          ],
          sub: 'Critical thinking is the skill that never expires.',
        },
        {
          type: 'concept',
          eyebrow: 'Hallucination',
          icon: '🌀',
          title: 'AI can make things up — and sound completely certain while doing it.',
          body: [
            "The term for this is 'hallucination.' AI doesn't lie intentionally — it doesn't have intentions. But it's designed to generate plausible-sounding text, and sometimes plausible-sounding is wrong.",
            "AI might invent a book that doesn't exist, cite a study that was never done, or state a fact that's simply incorrect — all with perfect grammar and total confidence.",
          ],
          highlight: "Confident doesn't mean correct. Always remember this.",
        },
        {
          type: 'concept',
          eyebrow: 'When to trust',
          icon: '✅',
          title: 'AI is reliable for some things — and not for others.',
          body: ["Knowing when to trust AI output — and when to verify — is one of the most valuable skills you can develop."],
          platformGrid: [
            { name: '✅ Generally reliable', detail: 'Summarizing text you provide, drafting based on your instructions, brainstorming, explaining concepts, editing your writing.' },
            { name: '⚠️ Verify before using', detail: 'Specific facts, statistics, quotes, dates, legal or medical information, news events, claims about real people.' },
            { name: '✅ Good for exploration', detail: 'Research starting points, generating options, thinking through decisions, getting different perspectives.' },
            { name: '⚠️ Use with care', detail: "Anything with real consequences — advice you'll act on, content you'll publish, information you'll share as fact." },
          ],
        },
        {
          type: 'concept',
          eyebrow: 'How to verify',
          icon: '🔍',
          title: 'A quick, practical fact-checking habit.',
          body: ["You don't need to verify everything — that would defeat the purpose. But for anything important, here's a fast habit:"],
          list: {
            items: [
              '<strong>For facts:</strong> Search the specific claim in Google or Perplexity. Look for a primary source.',
              '<strong>For quotes:</strong> Search the exact quote in quotes. Attributed quotes are often misattributed or invented.',
              "<strong>For numbers:</strong> Check the original study or report — not just AI's summary of it.",
              "<strong>For advice:</strong> Ask yourself: what's the consequence if this is wrong? Higher stakes = more verification.",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Privacy',
          icon: '🔒',
          title: 'Be thoughtful about what you share with AI.',
          body: [
            "When you type something into ChatGPT, it's processed on external servers. For most everyday tasks, that's completely fine. But there are things you should keep out of AI conversations:",
          ],
          list: {
            items: [
              "<strong>Don't share:</strong> Passwords, account numbers, Social Security numbers, or financial credentials.",
              "<strong>Don't share:</strong> Confidential business information your company wouldn't want public.",
              "<strong>Don't share:</strong> Personal health information you wouldn't want stored by a third party.",
              "<strong>You can share:</strong> General work contexts, public information, your own writing and ideas, industry questions.",
            ],
            negative: false,
          },
          body2: "A useful rule of thumb: if you wouldn't say it in a coffee shop with strangers around, think twice before typing it into AI.",
        },
        {
          type: 'concept',
          eyebrow: 'AI and bias',
          icon: '⚖️',
          title: 'AI reflects patterns — not truth.',
          body: [
            "AI learned from a massive amount of text written by humans. That means it can reflect human biases — cultural assumptions, historical patterns, gaps in representation.",
            "This doesn't make AI useless. It makes you a more important part of the process. Your judgment, your context, your knowledge of your specific situation is what AI is missing.",
          ],
          highlight: "AI is a powerful starting point. Your judgment is what makes the output actually good.",
        },
        {
          type: 'compare',
          eyebrow: 'Two approaches',
          title: 'Trust everything vs. trust thoughtfully.',
          bad: { label: 'Trusting blindly', text: 'ChatGPT said the regulation changed in 2022, so I included it in the report without checking.' },
          good: { label: 'Trusting thoughtfully', text: 'ChatGPT gave me a great starting point on the regulation — I confirmed the date and source before including it.' },
          highlight: "Verification doesn't slow you down much. It protects your credibility completely.",
        },
        {
          type: 'exercise',
          eyebrow: 'Try it now',
          icon: '🧪',
          title: 'Practice spotting an AI error.',
          body: ["Here's a way to build your verification instincts. It takes about 5 minutes."],
          prompt: "Step 1: Ask ChatGPT a specific factual question in your area of expertise — something you know well.\n\nStep 2: Read the response carefully. Notice anything wrong, oversimplified, or missing?\n\nStep 3: If everything looks right, ask it something more obscure — a specific date, statistic, or name.\n\nStep 4: Verify one claim using Google or Perplexity.\n\nThe goal: see for yourself that AI is helpful AND fallible. Both are true.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 2 complete',
          icon: '✅',
          title: 'You now use AI with both confidence and judgment.',
          summaryList: [
            'You know what hallucination is and why AI can be wrong while sounding certain.',
            'You know what AI is reliable for and what always needs verification.',
            'You have a quick fact-checking habit you can apply when stakes are high.',
            "You know what not to share with AI — and why.",
            "You understand that your judgment is what makes AI output actually trustworthy.",
          ],
        },
      ],
    },
    {
      id: 2,
      title: 'Staying Current Without Getting Overwhelmed',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 6 · Lesson 3',
          icon: '📡',
          title: "AI moves fast. Here's how to keep up without burning out.",
          body: [
            "If you've tried to follow AI news, you know how it feels: a new model launches every week, every newsletter says something is 'revolutionary,' and it's impossible to tell signal from hype.",
            "You don't need to keep up with everything. You need to stay aware of what's relevant to you — and ignore the rest. This lesson gives you a system for that.",
          ],
          sub: 'A calm, sustainable approach to a fast-moving field.',
        },
        {
          type: 'concept',
          eyebrow: 'The signal/noise problem',
          icon: '📻',
          title: "Most AI news isn't relevant to how you use AI.",
          body: [
            "The AI industry produces a staggering amount of content: model benchmarks, research papers, funding announcements, capability comparisons. Almost none of it directly affects how you use AI in your daily work.",
            "What matters to you is much narrower: new tools that solve problems you actually have, changes to tools you already use, and occasionally a genuinely major shift that everyone needs to know about.",
          ],
          highlight: 'You need 5% of AI news. The challenge is finding which 5%.',
        },
        {
          type: 'concept',
          eyebrow: 'Your information diet',
          icon: '🥗',
          title: 'One newsletter. One person to follow. One monthly habit.',
          body: ["Here's a minimal, effective setup for staying current:"],
          list: {
            items: [
              "<strong>One newsletter:</strong> Pick one that explains things clearly — The Rundown AI, TLDR AI, or Morning Brew's AI coverage. One is enough. Skim it 3 times a week.",
              "<strong>One person to follow:</strong> Find one voice on LinkedIn or YouTube who explains AI in plain English without constant hype. When they flag something, pay attention.",
              "<strong>One monthly habit:</strong> Set a 15-minute calendar block once a month. Ask ChatGPT: 'What are the most significant AI developments in the past month that matter for someone who [describe your work]?'",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Reading the news',
          icon: '📰',
          title: "How to evaluate 'big AI news' without getting swept up.",
          body: ["When something gets called a 'breakthrough' or 'game changer,' here's a quick filter:"],
          list: {
            items: [
              "<strong>Does it affect tools I actually use?</strong> If it's about a model you don't use, it might not matter yet.",
              "<strong>What does it actually do differently?</strong> Ignore the marketing language and look for the specific capability change.",
              "<strong>Is this available to me, or still in research?</strong> Many 'breakthroughs' take 12–18 months to reach end users.",
              "<strong>What would I do differently because of this?</strong> If the answer is nothing, move on.",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'The monthly review',
          icon: '📅',
          title: 'The 15-minute AI check-in that keeps you current.',
          body: ["Once a month, spend 15 minutes asking yourself three questions. That's it — no reading required beyond what you already do."],
          list: {
            items: [
              "<strong>Is my AI stack still working for me?</strong> Are there friction points? Tools I've stopped using?",
              "<strong>Is there something I've heard about that I should try?</strong> A tool a colleague mentioned, a feature that was added.",
              "<strong>What's one new thing I want to experiment with this month?</strong> Keep it to one — focus beats exploration.",
            ],
            negative: false,
          },
          highlight: 'Fifteen minutes a month is enough to stay ahead of 90% of people in your field.',
        },
        {
          type: 'concept',
          eyebrow: 'The bigger picture',
          icon: '🌊',
          title: "You don't need to catch every wave. You need to stay in the water.",
          body: [
            "The people who struggle most with AI aren't the ones who can't keep up — it's the ones who disengage entirely because it feels like too much to track.",
            "Your goal isn't to know about every tool. It's to stay curious, stay willing to try things, and occasionally update your setup when something clearly better comes along.",
          ],
          body2: "That's it. The bar is lower than the noise makes it seem.",
        },
        {
          type: 'exercise',
          eyebrow: 'Set it up',
          icon: '📅',
          title: 'Build your AI update routine right now.',
          body: ["This takes less than 5 minutes. Do it before you close this lesson."],
          prompt: "1. Pick one newsletter:\n   → Go to therundown.ai OR tldr.tech/ai and subscribe\n\n2. Set a monthly calendar reminder:\n   → Title it 'AI Monthly Check-In'\n   → Set it for 15 minutes on the first Monday of every month\n   → Paste this in the notes: 'Is my AI stack working? Anything new to try?'\n\n3. Find one voice to follow:\n   → Search LinkedIn for someone who writes about AI in plain English\n   → Follow them\n\nYou now have a system — not just good intentions.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 3 complete',
          icon: '✅',
          title: 'You have a sustainable system for staying current.',
          summaryList: [
            "You know why most AI news isn't relevant to you — and how to filter for what is.",
            'You have a minimal setup: one newsletter, one follow, one monthly habit.',
            "You have a 4-question filter for evaluating 'big AI news' without getting swept up.",
            "You've set up your monthly AI check-in so staying current happens automatically.",
          ],
        },
      ],
    },
    {
      id: 3,
      title: 'AI and Your Future — Real Talk',
      meta: '8 slides · ~6 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 6 · Lesson 4',
          icon: '🔮',
          title: "The questions everyone's thinking but not asking out loud.",
          body: [
            "Will AI take my job? Am I falling behind? What does this all mean for my career?",
            "These are real questions, and they deserve real answers — not reassurance for its own sake. This lesson is about the honest picture: what AI changes, what it doesn't, and what actually keeps you valuable.",
          ],
          sub: 'No hype. No fear. Just an honest look forward.',
        },
        {
          type: 'concept',
          eyebrow: 'The job question',
          icon: '💼',
          title: 'Will AI take my job? The honest answer.',
          body: [
            "The honest answer is: it depends on your job, and it's more complicated than headlines suggest.",
            "AI will automate specific tasks — repetitive ones, pattern-matching ones, high-volume but low-judgment ones. It's already doing this. The jobs most affected are the ones where most of the work is that kind of task.",
          ],
          list: {
            items: [
              '<strong>More affected:</strong> Data entry, basic writing, first-draft research, routine customer service, templated reports.',
              '<strong>Less affected:</strong> Roles requiring judgment, relationships, leadership, physical presence, creative direction.',
              '<strong>Most common reality:</strong> Your job changes — AI handles some tasks, you focus on higher-value work.',
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: "What's changing",
          icon: '🔄',
          title: "The shift isn't jobs disappearing. It's job descriptions changing.",
          body: [
            "Across most industries, the pattern isn't elimination — it's transformation. A marketing team that used to need 5 writers might need 2 writers plus AI tools. A researcher who used to spend 6 hours on a literature review might spend 90 minutes.",
            "This means the people who stay valuable are the ones who can <strong>direct AI</strong>, <strong>evaluate its output</strong>, and <strong>apply human judgment</strong> to what it produces.",
          ],
          highlight: "The skill isn't using AI. It's knowing when to trust it, when to push back, and when to take it further.",
        },
        {
          type: 'concept',
          eyebrow: 'What makes you irreplaceable',
          icon: '🌟',
          title: "The things AI genuinely can't do.",
          body: ["AI is powerful. It's also genuinely limited in ways that matter:"],
          list: {
            items: [
              "<strong>Real relationships.</strong> AI can write an email, but it can't build the trust that makes the email land.",
              "<strong>Contextual judgment.</strong> AI knows the general case. You know your specific client, team, or situation.",
              "<strong>Accountability.</strong> Someone has to own the decision. AI can help you make it — not make it for you.",
              "<strong>Creativity from lived experience.</strong> AI remixes patterns. You can draw on something no dataset contains.",
              "<strong>Adaptation in the moment.</strong> Reading a room, responding to the unexpected, knowing when to go off-script.",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'Staying relevant',
          icon: '📈',
          title: 'The T-shaped professional: broad knowledge, deep AI fluency.',
          body: [
            "The concept of 'T-shaped' skills — broad awareness across many areas, deep expertise in one — is more relevant than ever.",
            "The people who will thrive are the ones who combine <strong>domain expertise</strong> (their actual field) with <strong>AI fluency</strong> (knowing how to use these tools well). You already have the domain expertise. That's what you've brought to Clearly, AI. What you've added is the fluency.",
          ],
          highlight: 'Your expertise tells AI what to do. AI fluency tells you how to ask.',
        },
        {
          type: 'concept',
          eyebrow: 'The upside',
          icon: '☀️',
          title: 'The part no one talks about: what AI gives you back.',
          body: [
            "Most conversations about AI and work focus on threat. Here's what often gets left out:",
            "AI gives time back. Time you used to spend on first drafts, summarizing documents, formatting reports, searching for information — that time can now go toward the work that actually matters to you. The creative parts. The relationship parts. The parts that require you specifically.",
          ],
          body2: "That's not nothing. For a lot of people, it's the best thing about AI.",
        },
        {
          type: 'exercise',
          eyebrow: 'Reflect',
          icon: '✍️',
          title: "Write your 'AI advantage' statement.",
          body: ["This takes 5 minutes and is worth keeping. It's a short statement about how you specifically become more valuable with AI."],
          prompt: "Complete these sentences:\n\nMy core expertise is: [what you actually know and do well]\n\nThe tasks AI can help me with are: [specific tasks from your week]\n\nWith that time back, I can focus more on: [the higher-value or more human parts of your work]\n\nThat makes me more valuable because: [name it directly]\n\nThis isn't a resume bullet. It's a personal clarity statement. Write it for yourself.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Lesson 4 complete',
          icon: '✅',
          title: 'You have an honest picture of AI and your future.',
          summaryList: [
            'You understand how AI affects work — tasks more than jobs, transformation more than elimination.',
            'You know what makes you genuinely irreplaceable: judgment, relationships, accountability, lived experience.',
            'You can articulate your T-shaped advantage: domain expertise + AI fluency.',
            "You've written your own AI advantage statement to make this concrete.",
          ],
        },
      ],
    },
    {
      id: 4,
      title: 'Your Next 90 Days',
      meta: '9 slides · ~7 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Module 6 · Lesson 5',
          icon: '🗓️',
          title: "Learning doesn't stop here. It just gets more <em>yours.</em>",
          body: [
            "You've completed the curriculum. But a course is a starting point, not a finish line. What happens in the next 90 days will determine whether the skills you've built become habits — or fade.",
            'This lesson gives you a concrete plan for what to do after you close this module.',
          ],
          sub: 'The next 90 days matter more than the last 6 modules.',
        },
        {
          type: 'concept',
          eyebrow: 'Three habits',
          icon: '🔁',
          title: 'The 3 habits that separate AI users from AI enthusiasts.',
          body: ["You can 'know about' AI your whole life and never get any real value from it. The people who actually benefit have three habits in common:"],
          habitCards: [
            { num: '1', name: 'Daily friction moments', desc: "When you hit something annoying or time-consuming — a long email to write, a document to summarize — your first instinct is to open AI and try it there first." },
            { num: '2', name: 'Weekly reflection', desc: "Once a week, ask yourself: where did AI help me this week? Where did I forget to use it? Five minutes of reflection builds the habit faster than anything else." },
            { num: '3', name: 'Monthly tool update', desc: "Your monthly 15-minute AI check-in. Is your stack still working? Is there something worth adding? One focused question per month." },
          ],
        },
        {
          type: 'concept',
          eyebrow: 'The 30-day challenge',
          icon: '📆',
          title: 'One specific thing to try every day for 30 days.',
          body: ["The fastest way to make AI a habit: use it every day for 30 days, even for small things. Here's a simple starting challenge:"],
          list: {
            items: [
              "<strong>Week 1:</strong> Use ChatGPT for every piece of writing you'd normally do yourself. Even short emails. Just try it first.",
              '<strong>Week 2:</strong> Use AI for one research question per day — things you\'d normally search for. Notice the difference in quality.',
              "<strong>Week 3:</strong> Try one new tool or feature you haven't used yet. One per day, even briefly.",
              "<strong>Week 4:</strong> Create something with AI you couldn't have created on your own — a presentation, a content batch, a plan.",
            ],
            negative: false,
          },
        },
        {
          type: 'concept',
          eyebrow: 'How to keep improving',
          icon: '📈',
          title: 'The learn-try-teach loop.',
          body: [
            "The most effective way to deepen any skill — including AI — is the learn-try-teach loop:",
            "<strong>Learn</strong> something new (a prompt technique, a tool feature, a workflow). <strong>Try</strong> it on something real within 24 hours. <strong>Teach</strong> it to someone — explain it to a colleague, share it in a team meeting, write a quick post about it.",
          ],
          highlight: 'Teaching forces understanding. The moment you explain something to someone else, you truly own it.',
        },
        {
          type: 'concept',
          eyebrow: 'Share what you know',
          icon: '🤝',
          title: "You're now ahead of most people in your network.",
          body: [
            "One of the fastest ways to cement your own knowledge — and become genuinely valuable — is to help others around you get started.",
            "You don't need to be an expert. You just need to be one step further along. Show a colleague how to use ChatGPT for a task they struggle with. Share a prompt that saved you time. Recommend Clearly, AI to someone who's been curious but intimidated.",
          ],
          body2: "This isn't altruistic — it's also strategic. Being the person who helps others with AI is a career asset.",
        },
        {
          type: 'concept',
          eyebrow: "What's next",
          icon: '🗺️',
          title: 'Where to go from here.',
          body: ["You've built a foundation. Here's how to keep building:"],
          list: {
            items: [
              '<strong>Keep your AI stack active.</strong> Daily use beats occasional experimentation.',
              '<strong>Follow your monthly review routine.</strong> 15 minutes a month keeps you current without overwhelm.',
              '<strong>Stay connected.</strong> Look for Clearly, AI community access — learning alongside others accelerates everything.',
              '<strong>Advanced topics to explore on your own:</strong> Custom GPTs, AI automation (Zapier AI), voice AI, AI for specific industries.',
              "<strong>If you want to go deeper:</strong> The Clearly Pro track will be live soon — weekly coaching, 1:1 AI audits, and cohort courses.",
            ],
            negative: false,
          },
        },
        {
          type: 'exercise',
          eyebrow: 'Plan it',
          icon: '✍️',
          title: 'Write your 90-day AI plan.',
          body: ["Make it real by writing it down. This doesn't need to be elaborate — it needs to be specific."],
          prompt: "My AI stack (tools I'll use regularly):\n• Primary AI: [ChatGPT / Claude / other]\n• Image tool: [name or 'skip for now']\n• Transcription: [name or 'skip for now']\n• Specialized tool: [name or 'skip for now']\n\nMy 30-day challenge starts: [date]\n\nOne colleague I'll share AI with: [name]\n\nMy monthly check-in is scheduled for: [date — first Monday of each month]\n\nThe one area of work I most want AI to help me with: [be specific]\n\nSave this somewhere you'll see it.",
        },
        {
          type: 'concept',
          eyebrow: 'One last thought',
          icon: '💬',
          title: 'The thing that matters most.',
          body: [
            "You came into this course as someone who wasn't sure AI was for you. That took something — curiosity, willingness to try, patience with yourself when things didn't make sense immediately.",
            "What you've built isn't just skills. It's a relationship with a new kind of tool that will be part of your professional life for a long time. You get to shape what that looks like. You've already started.",
          ],
          highlight: "You didn't just learn about AI. You decided to understand it. That's the whole difference.",
        },
        {
          type: 'takeaway',
          eyebrow: 'Course complete · You made it.',
          icon: '🎓',
          title: "You've completed Clearly, AI.",
          summaryList: [
            'You have three habits to make AI a permanent part of how you work.',
            'You have a 30-day challenge to turn that intention into actual behavior.',
            'You have a 90-day plan — written and specific.',
            'You have the learn-try-teach loop to keep improving on your own.',
            'You know where to go next.',
          ],
          gradBlock: {
            icon: '🎓',
            title: "Congratulations. You've completed all 6 modules.",
            body: "You came in as someone curious about AI. You're leaving as someone who uses it. That's not a small thing. Most people never make that jump.\n\nWelcome to a very small group of people who actually know how to use AI — not just talk about it.",
            name: 'From the team at Clearly, AI — thank you for showing up.',
          },
        },
      ],
    },
  ],
  quiz: [
    {
      q: "What does 'hallucination' mean in the context of AI?",
      options: [
        'When AI generates images instead of text',
        'When AI confidently produces false or made-up information',
        'When AI takes longer than expected to respond',
        'When AI refuses to answer a sensitive question',
      ],
      correct: 1,
      feedback: "Hallucination is when AI generates plausible-sounding but incorrect information — with full confidence. It doesn't know it's wrong. That's why verification matters.",
    },
    {
      q: 'Which of these should you NEVER share with an AI chatbot?',
      options: [
        'General questions about your industry or field',
        'Publicly available facts you want explained',
        'Passwords, financial credentials, or highly sensitive personal data',
        'Descriptions of your work style or communication preferences',
      ],
      correct: 2,
      feedback: "Passwords, financial account numbers, and sensitive credentials should never be shared with AI tools. Your inputs are processed on external servers, so treat them like a public space.",
    },
    {
      q: "What is the 'learn-try-teach' loop?",
      options: [
        'A method for training AI models on new data',
        'Learning something new, applying it to a real task, then explaining it to someone else',
        'A ChatGPT prompting technique for better results',
        'A way to evaluate whether a new AI tool is worth adopting',
      ],
      correct: 1,
      feedback: "The learn-try-teach loop accelerates skill development: you learn something, apply it quickly, and then explain it to others — which forces real understanding and cements the skill.",
    },
    {
      q: "When AI gives you a surprising or important fact, what's the smartest response?",
      options: [
        'Trust it — AI is trained on more information than any human',
        'Ignore it — AI is too unreliable to use for facts',
        'Ask AI the same question twice to confirm the answer',
        'Verify it against a credible primary source before acting on it',
      ],
      correct: 3,
      feedback: "The right habit is to verify important facts, especially before acting on them or sharing them. AI can be very accurate — and very wrong — on the same topic. Primary sources are your anchor.",
    },
    {
      q: 'What best describes how AI is affecting most jobs right now?',
      options: [
        'AI is eliminating most professional jobs within 5 years',
        'AI has no real effect on knowledge work yet',
        'AI is automating specific tasks within jobs, shifting what people focus on',
        'Only technical roles are affected by AI',
      ],
      correct: 2,
      feedback: "The most accurate picture is task transformation, not wholesale job elimination. AI handles specific tasks — especially repetitive, pattern-based ones — while humans shift toward higher-judgment work.",
    },
  ],
}

export default module6
