import type { CourseData } from './types'

const starterCourse: CourseData = {
  moduleId: 0,
  title: '10 Things You Can Do With AI Today',
  subtitle: 'Free Starter Course',
  lessons: [
    {
      id: 0,
      title: 'Your First 5 AI Wins',
      meta: '7 slides · ~8 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Free Starter Course',
          icon: '🚀',
          title: '10 things you can do with AI <em>today.</em>',
          body: [
            'No tech skills required. No jargon. Just 10 practical things you can try right now — in plain English.',
            'Each one comes with a ready-to-use prompt you can copy and paste directly into ChatGPT, Claude, or Gemini.',
          ],
          sub: 'Start anywhere. There\'s no wrong order.',
        },
        {
          type: 'exercise',
          eyebrow: '01 · Write',
          icon: '✉️',
          title: 'Write any email in 30 seconds.',
          body: ['Give AI the key points you want to cover and it will write a clear, polished email for you — ready to copy, tweak, and send. Works for work emails, follow-ups, complaints, thank-you notes, and more.'],
          prompt: 'Write a friendly follow-up email to a client named John. We met last week and discussed working together on a marketing project. Keep it warm, short, and professional.',
          body2: 'Edit the result to match your voice, then send. You just saved 15 minutes.',
        },
        {
          type: 'exercise',
          eyebrow: '02 · Summarize',
          icon: '📋',
          title: 'Summarize anything instantly.',
          body: ['Paste in a long article, email thread, report, or document and ask AI to give you just the key points. No more reading things twice trying to find what actually matters.'],
          prompt: 'Here\'s a long email thread. Summarize the key decisions made and any action items I need to follow up on: [paste the text here]',
          body2: 'This alone is worth the price of any AI subscription. Use it every day.',
        },
        {
          type: 'exercise',
          eyebrow: '03 · Brainstorm',
          icon: '💡',
          title: 'Brainstorm ideas — on demand.',
          body: ['AI never runs dry on ideas. Gift ideas, business names, dinner themes, marketing angles, vacation spots — describe what you\'re looking for and get a dozen options immediately.'],
          prompt: 'Give me 10 creative names for a small bakery that specializes in gluten-free treats. Warm, friendly, memorable. Nothing too cutesy.',
          body2: 'You don\'t have to use any of the suggestions as-is. They\'re springboards.',
        },
        {
          type: 'exercise',
          eyebrow: '04 · Research',
          icon: '🔍',
          title: 'Get a straight answer to any question.',
          body: ['Skip the search results, the ads, and the ten tabs you have to open. Ask AI your question directly and get a clear, useful answer — you can even ask follow-up questions to dig deeper.'],
          prompt: 'Explain what a Roth IRA is and whether it makes sense for someone in their 40s. Plain English only — no financial jargon.',
          body2: 'Always verify specific facts and figures before acting on them. AI is a great starting point, not a final source.',
        },
        {
          type: 'exercise',
          eyebrow: '05 · Polish',
          icon: '✏️',
          title: 'Proofread and polish your writing.',
          body: ['Paste anything you\'ve written — an email, a bio, a review, a cover letter — and ask AI to clean it up, fix mistakes, and improve the tone. You keep your voice; it just makes it shine.'],
          prompt: 'Proofread this and make it sound more professional. Fix any grammar issues and tighten the language, but keep my voice: [paste your text]',
          body2: 'Great for anything that goes to a client, a boss, or the public.',
        },
        {
          type: 'takeaway',
          eyebrow: 'Halfway there',
          icon: '✨',
          title: 'Five down. Five more to go.',
          body: [
            'You\'ve just seen five genuinely useful things you can do with AI today — no setup, no learning curve.',
            'The next lesson covers five more: social media, planning, decoding confusing documents, recipes, and writing your bio.',
          ],
          highlight: 'Each prompt above works in ChatGPT, Claude, Gemini, or any major AI tool. Free accounts are fine.',
        },
      ],
    },
    {
      id: 1,
      title: '5 More Things — Plus Tips to Make It Work Better',
      meta: '8 slides · ~9 min',
      slides: [
        {
          type: 'intro',
          eyebrow: 'Free Starter Course · Lesson 2',
          icon: '🎯',
          title: 'Five more practical wins.',
          body: ['Ready for the second half? These five go a little deeper — planning, research, decoding, cooking, and putting yourself out there professionally.'],
          sub: 'Plus three tips that make every AI conversation better.',
        },
        {
          type: 'exercise',
          eyebrow: '06 · Content',
          icon: '📱',
          title: 'Write a week of social media posts.',
          body: ['Tell AI about your business and what you want to say, and get a full week of ready-to-post content — captions, hashtag suggestions, and all. Works for Instagram, Facebook, LinkedIn, and more.'],
          prompt: 'Write 5 Instagram posts for a local coffee shop called Morning Grounds. Friendly, casual tone. Mix of behind-the-scenes moments, product spotlights, and community vibes.',
          body2: 'Swap in your own business details. Adjust the tone. You\'ll have a week of content in under two minutes.',
        },
        {
          type: 'exercise',
          eyebrow: '07 · Plan',
          icon: '🗓️',
          title: 'Plan a trip, event, or project.',
          body: ['Give AI your dates, budget, and what you care about — and get a complete, practical plan. Itineraries, to-do lists, party timelines, project outlines. It handles the thinking so you don\'t have to.'],
          prompt: 'Plan a 4-day trip to Nashville for two people. We like live music, good food, and history. Budget around $1,500 total. Give me a day-by-day itinerary.',
          body2: 'Works just as well for planning a dinner party, a home renovation project, or a work presentation.',
        },
        {
          type: 'exercise',
          eyebrow: '08 · Decode',
          icon: '📄',
          title: 'Decode confusing documents.',
          body: ['Medical reports, insurance policies, legal contracts, HOA rules — paste a confusing paragraph and ask AI to explain it in plain English. You\'ll actually understand what you signed.'],
          prompt: 'Here\'s a paragraph from my insurance policy: [paste the text]. What does this actually mean in plain English? What should I know or watch out for?',
          body2: 'Important: for legal or medical decisions, always confirm with a qualified professional. Use AI to understand — not to replace expert advice.',
        },
        {
          type: 'exercise',
          eyebrow: '09 · Cook',
          icon: '🍳',
          title: "Turn what's in your fridge into dinner.",
          body: ['Tell AI what ingredients you have and it will generate a full recipe — including steps, tips, and even substitutions if you\'re missing something. No more "I don\'t know what to make."'],
          prompt: 'I have chicken thighs, garlic, lemons, olive oil, and some fresh rosemary. What can I make for dinner tonight? Give me a simple, step-by-step recipe.',
          body2: 'This one surprises people every time. Try it tonight.',
        },
        {
          type: 'exercise',
          eyebrow: '10 · Introduce Yourself',
          icon: '👤',
          title: 'Write your bio, intro, or professional summary.',
          body: ['Tell AI who you are and what you do, and get a polished, professional bio in seconds. Use it for LinkedIn, a website, a speaking introduction — wherever you need to put your best foot forward.'],
          prompt: "Write a short professional bio for me. I'm a 52-year-old office manager with 20 years in healthcare administration. I'm known for being organized, warm, and great with people. Keep it to 3–4 sentences.",
          body2: 'Swap in your own details. Read it back, adjust what doesn\'t sound like you, and you\'re done.',
        },
        {
          type: 'concept',
          eyebrow: 'A few tips to make it work even better',
          icon: '🧭',
          title: 'Three habits that separate good AI users from great ones.',
          body: [
            '<strong>Be specific.</strong> The more detail you give, the better the result. Include your audience, tone, and any constraints. Treat it like briefing a helpful assistant.',
            '<strong>Keep the conversation going.</strong> Not quite right? Just say so. "Make it shorter," "make it warmer," or "try a different angle" all work. You can go back and forth as many times as you want.',
            '<strong>Always review before you use it.</strong> AI is a starting point, not a final draft. Read it through, make it your own, and fact-check anything important. You\'re still in charge.',
          ],
        },
        {
          type: 'takeaway',
          eyebrow: 'You\'re ready.',
          icon: '🏆',
          title: "You just learned 10 things most people don't know how to do.",
          body: [
            'Every item on this list works today, with a free AI account, in less time than it takes to make coffee.',
            'This is just the beginning. The full Clearly, AI course goes deeper — real workflows, smarter prompts, and tools that change how you work every single day.',
          ],
          highlight: 'Ready to go deeper? The full course covers 6 modules, 30 lessons, and gives you a personal AI workflow you\'ll use for years.',
        },
      ],
    },
  ],
}

export default starterCourse
